<?php
/**
 * Implementation of hook_civicrm_buildForm().
 */
function civicrm_ckeditor_civicrm_buildForm($formName, &$form) {
  foreach ($form->_elements as $element) {
    if($element->_type == 'CKeditor') {
      $path = base_path().drupal_get_path('module', 'civicrm_ckeditor');
      $ckeditor_inline_js = "
        $( function( ) {
          CKEDITOR.config.customConfig= '$path/ckeditor.config.js';
          CKEDITOR.config.toolbar = 'CiviCRM';
        });
        ";
      drupal_add_js($ckeditor_inline_js, 'inline');
    }
  }
}
