<?php
/**
 * Implementation of hook_civicrm_buildForm().
 */
function civicrm_twaddress_civicrm_buildForm($formName, &$form) {
  static $add;
  // we don't support outside of civicrm yet
  if(arg(0) != 'civicrm'){
    return;
  }

  // we don't support ajax form
  $deny = array('CRM_Event_Form_ManageEvent_Location');
  if(in_array($formName,$deny)){
    return;
  }
  
  // we don't process report form
  if(strpos($formName, 'Report_Form')){
    return;
  }
  // we don't change form on step 2 / 3 / 4
  if(strpos($formName, 'Confirm') || strpos($formName, 'ThankYou')){
    return;
  }
  //
  $enable = TRUE;
  $form_name = $form->_attributes['name'];
  foreach ($form->_elements as $k => $e) {
    $name = $e->_attributes['name'];
    if(strstr($name, 'postal_code')){
      $override['zipName']['key'] = $name;
      $override['zipName']['default'] = $form->getElement($name)->_findValue($form->_defaultValues);
    }
    if(strstr($name, 'state_province')){
      $override['countyName']['key'] = $name;
      foreach($e->_options as $v){
        if($v['attr']['value']){
          $county_options[$v['attr']['value']] = $v['text'];
        }
      }
      $default = $form->getElement($name)->_findValue($form->_defaultValues);
      $override['countyName']['default'] = $county_options[$default];
      $form->_elements[$k]->_label = '縣市';
    }
    if(strstr($name, 'city')){
      // hide field
      $form->_elements[$k]->_label = '鄉鎮市區';

      $default = $form->getElement($name)->_findValue($form->_defaultValues);
      $override['areaName']['key'] = '_'.$name;
      $override['areaName']['name'] = $name;
      $override['areaName']['default'] = $default;
    }
    if(strstr($name, 'country')){
      $enable = FALSE;
    }
  }

  if(count($override)>=3 && $enable){
    if(!$add){
      /*
      if(arg(0) != 'civicrm'){
        drupal_add_js( 'var cj = jQuery.noConflict(); $ = cj;', 'inline' );
      }
      */
      $path = drupal_get_path("module",'civicrm_twaddress');
      drupal_add_js($path."/twzipcode.js");
      $add = 1;
    }
    foreach($county_options as $v => $l){
      $cjs .= 'county['.$v.']="'.$l.'";'."\n";
    }
    $insert = "<select name='{$override['areaName']['key']}' class='form-select'></select>";

    $js = '
    var county = new Array();
    '.$cjs.'
    function getcounty(n){
      return county[n] ? county[n] : n;
    }
    cj(document).ready(function(){
      cj("'.$insert.'").insertAfter("input[name=\''.$override['areaName']['name'].'\']");
      cj("input[name=\''.$override['areaName']['name'].'\']").hide();
      cj("select[name=\''.$override['areaName']['key'].'\']").change(function(){
        var v = $(this).val();
        cj("input[name=\''.$override['areaName']['name'].'\']").val(v);
      });

      cj("form[name='.$form_name.']").twzipcode({
        zipName:"'.$override['zipName']['key'].'",
        countyName:"'.$override['countyName']['key'].'",
        areaName:"'.$override['areaName']['key'].'",
        zipSel:"'.$override['zipName']['default'].'",
        countySel:"'.$override['countyName']['default'].'",
        areaSel:"'.$override['areaName']['default'].'"
      });

      var x;
      for(x in county){
        var county_name = county[x];
        var county_id = x;
        cj("select[name=\''.$override['countyName']['key'].'\'] option[value=\'"+county_name +"\']").each(function(){
          $(this).val(county_id);
        });
      }
    });
    ';
    drupal_add_js($js , 'inline');
  }
}
