<?php
/**
 * Implementation of hook_civicrm_buildForm().
 */
function civicrm_twaddress_civicrm_buildForm($formName, &$form) {
  static $add;
  // we don't support outside of civicrm yet
  if(arg(0) != 'civicrm'){
    return;
  }
  
  if($_GET['snippet']){
    return;
  }

  // we don't support ajax form
  $deny = array();
  if(in_array($formName,$deny)){
    return;
  }
  
  // we don't process report form
  if(strpos($formName, 'Report_Form')){
    return;
  }
  // we don't change form on step 2 / 3 / 4
  if(strpos($formName, 'Confirm') || strpos($formName, 'ThankYou')){
    return;
  }
  //
  $enable = TRUE;
  $form_name = $form->_attributes['name'];
  foreach ($form->_elements as $k => $e) {
    $name = $e->_attributes['name'];
    if(strstr($name, 'postal_code') && !strstr($name,'postal_code_suffix')){
      preg_match("/\[([0-9])\]/", $name, $matches);
      $key = $matches[1] ? $matches[1] : 1;
      $override['zipName'][$key]['key'] = $name;
      $override['zipName'][$key]['default'] = $form->getElement($name)->_findValue($form->_defaultValues);
    }
    if(strstr($name, 'state_province')){
      preg_match("/\[([0-9])\]/", $name, $matches);
      $key = $matches[1] ? $matches[1] : 1;
      $override['countyName'][$key]['key'] = $name;
      foreach($e->_options as $v){
        if($v['attr']['value']){
          $county_options[$v['attr']['value']] = $v['text'];
        }
      }
      $default = $form->getElement($name)->_findValue($form->_defaultValues);
      $override['countyName'][$key]['default'] = $county_options[$default];
      $form->_elements[$k]->_label = '縣市';
    }
    if(strstr($name, 'city')){
      preg_match("/\[([0-9])\]/", $name, $matches);
      $key = $matches[1] ? $matches[1] : 1;
      // hide field
      $form->_elements[$k]->_label = '鄉鎮市區';

      $default = $form->getElement($name)->_findValue($form->_defaultValues);
      $override['areaName'][$key]['key'] = '_'.$name;
      $override['areaName'][$key]['name'] = $name;
      $override['areaName'][$key]['default'] = $default;
    }
    if(strstr($name, 'country')){
      $enable = FALSE;
    }
  }

  if(count($override)>=3 && $enable){
    if(!$add){
      $path = drupal_get_path("module",'civicrm_twaddress');
      drupal_add_js($path."/twzipcode.js");
      $add = 1;
    }
    foreach($override['areaName'] as $k => $v){
      $count++;

      $insert = "<select name='{$override['areaName'][$k]['key']}' class='form-select'></select>";

      $js = '
      cj(document).ready(function(){
        if( cj("input[name=\''.$override['areaName'][$k]['name'].'\']").length ){
          cj("'.$insert.'").insertAfter("input[name=\''.$override['areaName'][$k]['name'].'\']");
          cj("input[name=\''.$override['areaName'][$k]['name'].'\']").hide();
          cj("select[name=\''.$override['areaName'][$k]['key'].'\']").change(function(){
            var v = $(this).val();
            cj("input[name=\''.$override['areaName'][$k]['name'].'\']").val(v);
          });

          cj("form[name='.$form_name.']").twzipcode({
            zipName:"'.$override['zipName'][$k]['key'].'",
            countyName:"'.$override['countyName'][$k]['key'].'",
            areaName:"'.$override['areaName'][$k]['key'].'",
            zipSel:"'.$override['zipName'][$k]['default'].'",
            countySel:"'.$override['countyName'][$k]['default'].'",
            areaSel:"'.$override['areaName'][$k]['default'].'"
          });
        }

      });
      ';
      drupal_add_js($js , 'inline');
    }
  }
}
