<?php

/**
 * Implementation of hook_buildForm()
 */
function civicrm_legalid_civicrm_buildForm( $formName, &$form ) {
  if ($formName == 'CRM_Contact_Form_Contact') {
    // ssn
    $form->addElement('text', 'legal_identifier', ts('Legal Identifier'));

    // this will retrieve the contact id
    $contactID = $form->getVar( '_contactId' );

    if ( $contactID ) {
      // setdefault if legal_identifier is saved
      $defaults['legal_identifier'] = CRM_Core_DAO::singleValueQuery( "SELECT legal_identifier FROM civicrm_contact WHERE id = {$contactID}" );
      $form->setdefaults( $defaults );
    }
  }
}

/**
 * Implementation of hook_validate()
 */
function civicrm_legalid_civicrm_validate( $formName, &$fields, &$files, &$form ) {
  $errors = array( );
  if ($formName == 'CRM_Contact_Form_Contact') {
    $contactID = $form->getVar( '_contactId' );
    if ( !empty($fields['legal_identifier']) ) {
/*
TODO: need to change to Taiwan id verify
      $preg = "/^\\d{3}[- ]?\\d{2}[- ]?\\d{4}$/";
      $match = preg_match($preg, $fields['legal_identifier'] ) ? true : false;
      if ( !$match ) {
        $errors['legal_identifier'] = ts('Enter valid SSN number.');
      }
*/
      // length
      /*
      if(strlen($fields['legal_identifier']) < 10){
        $errors['legal_identifier'] = ts('Enter valid personal identifier number.');
      }
      */

      // duplicate
      $qvar = array( 
        1 => array($fields['legal_identifier'], 'String' ),
      );
      $sql = "SELECT id, display_name FROM civicrm_contact WHERE is_deleted = 0 AND legal_identifier = %1";
      if($contactID){
        // when update
        $qvar[2] = array($contactID, 'Integer' );
        $sql .= " AND id != %2";
      }
      $dao = CRM_Core_DAO::executeQuery($sql, $qvar);
      $dao->fetch();
      if($dao->id){
        $link = CRM_Utils_System::href($dao->display_name, 'civicrm/contact/add', 'reset=1&action=update&context=search&cid='.$dao->id);
        $errors['legal_identifier'] = ts("Duplicate legal identifier with %1", array(1 => $link));
      }
    }
  }
  return empty( $errors ) ? true : $errors;
}

/**
 * Implementation of hook_postProcess()
 */
function civicrm_legalid_civicrm_postProcess( $formName, &$form ) {
  if ($formName == 'CRM_Contact_Form_Contact') {
    // this will give you the SSN submitted value
    $values = $form->exportValues( );
    $legalid = CRM_Utils_Type::escape($values['legal_identifier'], 'String');

    // this will retrieve the contact id
    $contactID = $form->getVar( '_contactId' );

    // we need to check if entry exists for current contact in training_ssn table
    // if yes then update else insert
    $qvar = array(1 => array($contactID, 'Integer' ));
    $exists_legalid = CRM_Core_DAO::singleValueQuery( "SELECT id FROM civicrm_contact WHERE id = %1", $qvar);

    if ($exists_legalid) {
      $qvar[2] = array($legalid, 'String' );
      $query = "UPDATE civicrm_contact SET legal_identifier = %2 WHERE id = %1";
      CRM_Core_DAO::executeQuery($query, $qvar);
    }
    else {
      // drop here.
      // it's not possible to save non conatact table
    }
  }
}

/**
 * Implementation of hook_pageRun()
 */
function civicrm_legalid_civicrm_pageRun( &$page ) {
  if ( is_a( $page, 'CRM_Contact_Page_View_Summary' ) ) {
     // this will retrieve the contact id
    $contactID = $page->getVar( '_contactId' );
    // get the ssn number and set it to the templaet
    $qvar = array(1 => array($contactID, 'Integer' ));
    $legalid = CRM_Core_DAO::singleValueQuery( "SELECT legal_identifier FROM civicrm_contact WHERE id = %1", $qvar);
    $page->assign('legal_identifier', $legalid);
  }
}
