<?php
/**
 * Implementation of hook_civicrm_buildForm()
 */
function civicrm_instrument_civicrm_buildForm($form_name, &$form){
  switch($form_name){
    // contribution page settings
    case 'CRM_Contribute_Form_ContributionPage_Amount':
    case 'CRM_Event_Form_ManageEvent_Registration':
      if($entity_id = $_GET['id']){
        $entity_table = $form_name == 'CRM_Contribute_Form_ContributionPage_Amount' ? 'civicrm_contribution_page' : 'civicrm_event';

        $payment_instruments = CRM_Core_DAO::singleValueQuery("SELECT payment_instruments FROM civicrm_instrument WHERE entity_id = {$entity_id} AND entity_table = '{$entity_table}'");
        $payment_instruments = unserialize($payment_instruments);

        $gid = CRM_Core_DAO::singleValueQuery("SELECT id FROM civicrm_option_group WHERE name LIKE 'payment_instrument'");
        $option = CRM_Core_DAO::executeQuery("SELECT * FROM civicrm_option_value WHERE option_group_id = {$gid} AND is_active = 1");
        while($option->fetch()){
          $form_name = preg_replace('/[^0-9a-z]+/i', '_', strtolower($option->name));
          $options[$form_name] = array(
            'default' => $payment_instruments[$form_name] ? 1: 0,
            'label' => $option->label,
          );
        }
        drupal_add_js(civicrm_instrument_js($options, $entity_table), 'inline');
      }
      break;
  }
}

/**
 * Implementation of hook_civicrm_postProcess()
 */
function civicrm_instrument_civicrm_postProcess($form_name, &$form){
  switch($form_name){
    // contribution page settings
    case 'CRM_Contribute_Form_ContributionPage_Amount':
    case 'CRM_Event_Form_ManageEvent_Registration':
      $entity_table = $form_name == 'CRM_Contribute_Form_ContributionPage_Amount' ? 'civicrm_contribution_page' : 'civicrm_event';
      $entity_id = $form->getVar('_id');
      $payment_instrument = $form->_submitValues['payment_instrument'];
      if($entity_id && !empty($payment_instrument)){
        CRM_Core_DAO::executeQuery("REPLACE INTO civicrm_instrument SET entity_id = {$entity_id}, entity_table='{$entity_table}', payment_instruments='".serialize($payment_instrument)."'");
      }
      break;
  }
}

/**
 * Payment instrument admin javascript
 *
 * Provide payment instrument optoins for contribution and 
 * event page administration.
 */ 
function civicrm_instrument_js($options, $entity_table){
  switch($entity_table){
    case 'civicrm_contribution_page':
      $css_id = 'amountFields';
      break;
    case 'civicrm_event':
      $css_id = 'registration';
      break;
  }
  $o = "<table class='form-layout-compressed'><tbody><tr>";
  $o .= "<th scope='row' class='label' width='20%'><label for='payment_instrument'>".ts('Payment Instrument').'</label></th>';
  $o .= "<td><div class='content'>";
  foreach($options as $k => $v){
    $checked = $v['default'] ? 'checked=checked' : '';
    $o .= "<div class='instrument-gw-wrapper'><label><input type='checkbox' name='payment_instrument[{$k}]' value='1' class='form-checkbox' $checked />".$v['label']."</label></div>";
  }
  $o .= '</div></td>';
  $o .= '</tr></tbody></table>';
  return '
  $(document).ready(function(){
    $("#crm-container #'.$css_id.'").before("'.$o.'");
  });';
}
