<?php

function civicrm_profile_redirect_menu(){
  $items['civicrm/download'] = array(
    'page callback' => 'civicrm_profile_redirect',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function civicrm_profile_redirect(){
  drupal_set_title(t("Thank you!"));
  if($download = $_SESSION['CiviCRM']['download']){
    unset($_SESSION['CiviCRM']['download']);
    $o = '<iframe width="1" height="1" frameborder="0" src="'.$download.'"></iframe>';
    $o .= t('If your download does not start, click <a href="!href">here</a> to procceed download.', array('!href' => $download));
    return $o;
  }
  else{
    drupal_goto(); 
  }
}

function civicrm_profile_redirect_civicrm_buildForm($formName, &$form ){
  if($formName == 'CRM_Profile_Form_Edit'){
    if($_GET['r']){
      // url decode / parse and validate
      $redirect = $_GET['r'];
      $session = CRM_Core_Session::singleton( );
      // only replace user context if we do not have a postURL
      $session->set('postURL', $redirect);
    }
    elseif($_GET['d']){
      $download = $_GET['d'];
      $session = CRM_Core_Session::singleton( );
      // only replace user context if we do not have a postURL
      $session->set('download', $download);
      $session->set('postURL', url("civicrm/download"));
    }
  }
}

function civicrm_profile_redirect_civicrm_postProcess($formName, &$form ){
  if( $formName == 'CRM_Profile_Form_Edit'){
    $session = CRM_Core_Session::singleton( );
    $redirect = $session->get('postURL');
    // url decode / parse and validate
    // only replace user context if we do not have a postURL
    $session->replaceUserContext( $redirect );
  }
}
