<?php
/*
 +--------------------------------------------------------------------+
 | CiviCRM version 3.3                                                |
 +--------------------------------------------------------------------+
 | Copyright CiviCRM LLC (c) 2004-2010                                |
 +--------------------------------------------------------------------+
 | This file is a part of CiviCRM.                                    |
 |                                                                    |
 | CiviCRM is free software; you can copy, modify, and distribute it  |
 | under the terms of the GNU Affero General Public License           |
 | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
 |                                                                    |
 | CiviCRM is distributed in the hope that it will be useful, but     |
 | WITHOUT ANY WARRANTY; without even the implied warranty of         |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
 | See the GNU Affero General Public License for more details.        |
 |                                                                    |
 | You should have received a copy of the GNU Affero General Public   |
 | License and the CiviCRM Licensing Exception along                  |
 | with this program; if not, contact CiviCRM LLC                     |
 | at info[AT]civicrm[DOT]org. If you have questions about the        |
 | GNU Affero General Public License or the licensing of CiviCRM,     |
 | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
 +--------------------------------------------------------------------+
*/

/**
 *
 * @copyright CiviCRM LLC (c) 2004-2010
 *
 */

/**
 * This class handles all SOAP client requests.
 *
 * @copyright CiviCRM LLC (c) 2004-2010
 *
 */

class CRM_Utils_SoapServer {

  /**
   * Number of seconds we should let a SOAP process idle before expiring the key.
   *
   * A value of 0 means no timeout.
   *
   * @var int
   */
  public static $soap_timeout = 0;

  /**
   * The cached user framework class name used for authentication.
   *
   * @var string
   */
  public $ufClass;

  /**
   * Class constructor.
   *
   * Caches the user framework class locally so it can be used
   * for authentication and validation.
   *
   * @param string $uf The user framework class name.
   */
  public function __construct() {
    // any external program which call SoapServer is responsible for
    // creating and attaching the session
    $args = func_get_args();
    $this->ufClass = array_shift($args);
  }

  /**
   * Simple ping function to test for liveness.
   *
   * @param string $var The string to be echoed back.
   *
   * @return string The PONG response containing the input and the previous key.
   */
  public function ping($var) {
    $session = CRM_Core_Session::singleton();
    $key = $session->get('key');
    $session->set('key', $var);
    return "PONG: $var ($key)";
  }

  /**
   * Verify a SOAP key.
   *
   * Checks that the provided key matches the stored SOAP key and has not expired.
   *
   * @param string $key The SHA1-hashed SOAP key generated by authenticate().
   *
   * @return void
   *
   * @throws \SoapFault If the key is invalid or expired.
   */
  public function verify($key) {
    $session = CRM_Core_Session::singleton();

    $soap_key = $session->get('soap_key');
    $t = time();

    if ($key !== sha1($soap_key)) {
      throw new SoapFault('Client', 'Invalid key');
    }

    if (self::$soap_timeout &&
      $t > ($session->get('soap_time') + self::$soap_timeout)
    ) {
      throw new SoapFault('Client', 'Expired key');
    }

    /* otherwise, we're ok.  update the timestamp */

    $session->set('soap_time', $t);
  }

  /**
   * Authenticate a user via the user framework class.
   *
   * Delegates authentication to the UF class and stores the SOAP key
   * and timestamp in the session upon success.
   *
   * @param string $name The login name.
   * @param string $pass The password.
   *
   * @return string The SHA1-hashed SOAP client key.
   *
   * @throws \SoapFault If the login credentials are invalid.
   */
  public function authenticate($name, $pass) {
    $ufClassName = $this->ufClass;
    $result = &$ufClassName::authenticate($name, $pass);

    if (empty($result)) {
      throw new SoapFault('Client', 'Invalid login');
    }

    $session = CRM_Core_Session::singleton();
    $session->set('soap_key', $result[2]);
    $session->set('soap_time', time());

    return sha1($result[2]);
  }

  /**
   * Handle a mailing bounce event via SOAP.
   *
   * @param string $key  The SOAP authentication key.
   * @param int    $job  The mailing job ID.
   * @param int    $queue The event queue ID.
   * @param string $hash The verification hash.
   * @param string $body The bounce message body.
   *
   * @return mixed The result from civicrm_mailer_event_bounce().
   */
  public function mailer_event_bounce($key, $job, $queue, $hash, $body) {
    $this->verify($key);
    $params = ['job_id' => $job,
      'event_queue_id' => $queue,
      'hash' => $hash,
      'body' => $body,
    ];
    return civicrm_mailer_event_bounce($params);
  }

  /**
   * Handle a mailing unsubscribe event via SOAP.
   *
   * @param string $key  The SOAP authentication key.
   * @param int    $job  The mailing job ID.
   * @param int    $queue The event queue ID.
   * @param string $hash The verification hash.
   *
   * @return mixed The result from civicrm_mailer_event_unsubscribe().
   */
  public function mailer_event_unsubscribe($key, $job, $queue, $hash) {
    $this->verify($key);
    $params = ['job_id' => $job,
      'event_queue_id' => $queue,
      'hash' => $hash,
    ];
    return civicrm_mailer_event_unsubscribe($params);
  }

  /**
   * Handle a domain-level mailing unsubscribe event via SOAP.
   *
   * @param string $key  The SOAP authentication key.
   * @param int    $job  The mailing job ID.
   * @param int    $queue The event queue ID.
   * @param string $hash The verification hash.
   *
   * @return mixed The result from civicrm_mailer_event_domain_unsubscribe().
   */
  public function mailer_event_domain_unsubscribe($key, $job, $queue, $hash) {
    $this->verify($key);
    $params = ['job_id' => $job,
      'event_queue_id' => $queue,
      'hash' => $hash,
    ];
    return civicrm_mailer_event_domain_unsubscribe($params);
  }

  /**
   * Handle a mailing resubscribe event via SOAP.
   *
   * @param string $key  The SOAP authentication key.
   * @param int    $job  The mailing job ID.
   * @param int    $queue The event queue ID.
   * @param string $hash The verification hash.
   *
   * @return mixed The result from civicrm_mailer_event_resubscribe().
   */
  public function mailer_event_resubscribe($key, $job, $queue, $hash) {
    $this->verify($key);
    $params = ['job_id' => $job,
      'event_queue_id' => $queue,
      'hash' => $hash,
    ];
    return civicrm_mailer_event_resubscribe($params);
  }

  /**
   * Handle a mailing subscribe event via SOAP.
   *
   * @param string $key    The SOAP authentication key.
   * @param string $email  The email address to subscribe.
   * @param string $domain The domain (unused in underlying call).
   * @param int    $group  The group ID to subscribe to.
   *
   * @return mixed The result from civicrm_mailer_event_subscribe().
   */
  public function mailer_event_subscribe($key, $email, $domain, $group) {
    $this->verify($key);
    $params = ['email' => $email,
      'group_id' => $group,
    ];
    return civicrm_mailer_event_subscribe($params);
  }

  /**
   * Handle a mailing subscription confirmation event via SOAP.
   *
   * @param string $key       The SOAP authentication key.
   * @param int    $contact   The contact ID.
   * @param int    $subscribe The subscription ID.
   * @param string $hash      The verification hash.
   *
   * @return mixed The result from civicrm_mailer_event_confirm().
   */
  public function mailer_event_confirm($key, $contact, $subscribe, $hash) {
    $this->verify($key);
    $params = ['contact_id' => $contact,
      'subscribe_id' => $subscribe,
      'hash' => $hash,
    ];
    return civicrm_mailer_event_confirm($params);
  }

  /**
   * Handle a mailing reply event via SOAP.
   *
   * @param string      $key       The SOAP authentication key.
   * @param int         $job       The mailing job ID.
   * @param int         $queue     The event queue ID.
   * @param string      $hash      The verification hash.
   * @param string      $bodyTxt   The plain text reply body.
   * @param string      $rt        The reply-to address.
   * @param string|null $bodyHTML   The HTML reply body, or NULL.
   * @param string|null $fullEmail The full email content, or NULL.
   *
   * @return mixed The result from civicrm_mailer_event_reply().
   */
  public function mailer_event_reply($key, $job, $queue, $hash, $bodyTxt, $rt, $bodyHTML = NULL, $fullEmail = NULL) {
    $this->verify($key);
    $params = ['job_id' => $job,
      'event_queue_id' => $queue,
      'hash' => $hash,
      'bodyTxt' => $bodyTxt,
      'replyTo' => $rt,
      'bodyHTML' => $bodyHTML,
      'fullEmail' => $fullEmail,
    ];
    return civicrm_mailer_event_reply($params);
  }

  /**
   * Handle a mailing forward event via SOAP.
   *
   * @param string $key   The SOAP authentication key.
   * @param int    $job   The mailing job ID.
   * @param int    $queue The event queue ID.
   * @param string $hash  The verification hash.
   * @param string $email The email address to forward to.
   *
   * @return mixed The result from civicrm_mailer_event_forward().
   */
  public function mailer_event_forward($key, $job, $queue, $hash, $email) {
    $this->verify($key);
    $params = ['job_id' => $job,
      'event_queue_id' => $queue,
      'hash' => $hash,
      'email' => $email,
    ];
    return civicrm_mailer_event_forward($params);
  }

  /**
   * Retrieve contact data via SOAP.
   *
   * @param string $key    The SOAP authentication key.
   * @param array  $params The parameters to pass to civicrm_contact_get().
   *
   * @return mixed The result from civicrm_contact_get().
   */
  public function get_contact($key, $params) {
    $this->verify($key);

    return civicrm_contact_get($params);
  }
}
