<?php
/**
 * Implementation of hook_civicrm_buildForm().
 */
function civicrm_phone_format_civicrm_buildForm($formName, &$form) {
  static $add;

  if($_GET['q'] != 'civicrm/event/register' && $_GET['q'] != 'civicrm/profile/create' && $_GET['q']!= 'civicrm/contribute/transact'){
//    return;
  }

  if(!$add){
    $form_name = $form->_attributes['name'];
    foreach ($form->_elements as $k => $e) {
      $name = $e->_attributes['name'];
      if(strstr($name, 'phone')){
        $path = drupal_get_path('module', 'civicrm_phone_format');
        drupal_add_js($path.'/js/jquery.maskedinput-1.3.min.js');
        drupal_add_js($path.'/civicrm_phone_format.js');
      }
    }
    $add = TRUE;
  }
}
