<?php
/**
 * Implementation of hook_init()
 */
function civicrm_nccc_init(){
/*
  $path = drupal_get_path('module', 'civicrm_nccc');
  drupal_add_css("$path/civicrm_nccc.css");
*/

  if(strstr($_GET['q'], 'payment-nccc')){
    $GLOBALS['conf']['cache'] = FALSE;
  }
}

/**
 * Implementation of hook_menu()
 */
function civicrm_nccc_menu(){
  return array(
    'payment-nccc/ipn' => array(
      'access callback' => true,
      'page callback' => 'civicrm_nccc_ipn',
      'page arguments' => array(2),
      'type' => MENU_CALLBACK,
      'weight' => 0,
      'file' => 'civicrm_nccc.ipn.inc',
    ),
  );
}


/**
 * Implementation of hook_civicrm_buildForm()
 */
function civicrm_nccc_civicrm_buildForm($form_name, &$form){
  switch($form_name){
    case 'CRM_Contribute_Form_Contribution_ThankYou':
      break;
    case 'CRM_Contribute_Form_Contribution_Main':
      break;
  }
}

/**
 * Implementation of hook_cron()
 */
function civicrm_nccc_cron(){
  // we don't need cron, yet
}

function civicrm_nccc_err($response_code = NULL, $bank_code = NULL){
  module_load_include('inc', 'civicrm_nccc', 'civicrm_nccc.err');
}

