<div class="crm-container" id="crm-connector-page">

{* ============================================================ *}
{* MCP Section                                                   *}
{* ============================================================ *}
{if $mcpEnabled}
<div class="crm-block crm-connector-mcp-block">
  <h3><i class="zmdi zmdi-input-composite"></i>MCP</h3>

  <div id="mcp-result-panel" style="display:none" class="crm-connector-result-panel">
    <div class="crm-connector-result-warning">
      <div class="crm-connector-security-notice"><i class="zmdi zmdi-alert-polygon"></i> {ts}Security notice: This URL contains sensitive credentials. Do not share it publicly. Store it only in a trusted backend service or server, and keep it confidential.{/ts}</div>
    </div>
    <div id="mcp-result-value" class="crm-connector-result-value"></div>
    <div class="crm-connector-result-actions">
      {ts}This information will not be shown again. Please copy and save it now.{/ts}
      <button id="btn-copy-mcp" class="button crm-button"><i class="zmdi zmdi-link"></i> {ts}Copy{/ts}</button>
      <span id="mcp-copy-confirm" style="display:none" class="crm-connector-copy-confirm">{ts}Copied{/ts}</span>
      <button id="btn-close-mcp" class="button crm-button crm-button-type-main" style="margin-left:16px"><i class="zmdi zmdi-close-circle"></i>{ts}I have copied it, close{/ts}</button>
    </div>
  </div>

  <div id="mcp-action-area">
    {if $mcpInfo.has_key}
      <button id="btn-reset-mcp" class="button crm-button crm-button-type-cancel">
        <i class="zmdi zmdi-refresh-sync"></i>{ts}Regenerate{/ts}
      </button>
      <button id="btn-revoke-key" class="button crm-button crm-button-type-cancel" style="margin-left:8px">
        <i class="zmdi zmdi-delete"></i>{ts}Revoke{/ts}
      </button>
    {else}
      <button id="btn-generate-mcp" class="button crm-button crm-button-type-main">
        <i class="zmdi zmdi-input-power"></i> {ts 1=MCP}New %1{/ts}
      </button>
    {/if}
  </div>

  {if $mcpInfo.has_key}
  <table class="crm-info-panel" style="margin-top:16px">
    <tr>
      <td class="label">{ts}MCP URL (masked){/ts}</td>
      <td><code>{$mcpInfo.masked_url|escape}</code></td>
    </tr>
    <tr>
      <td class="label">{ts}Generated Date{/ts}</td>
      <td>{if $mcpInfo.generated_date}{$mcpInfo.generated_date|crmDate}{else}-{/if}</td>
    </tr>
    <tr>
      <td class="label">{ts}Generated By{/ts}</td>
      <td>{if $mcpInfo.generated_by}{$mcpInfo.generated_by|escape}{else}-{/if}</td>
    </tr>
    <tr>
      <td class="label">{ts}Last Login{/ts}</td>
      <td>{if $mcpInfo.last_login}{$mcpInfo.last_login|crmDate}{else}-{/if}</td>
    </tr>
  </table>
  {/if}
</div>
{/if}

{* ============================================================ *}
{* API Explorer Section                                          *}
{* ============================================================ *}
{if $apiExplorerEnabled && $apiKeyInfo.has_key && !$mcpInfo.generated_date}
<div class="crm-block crm-connector-apikey-block" style="margin-top:24px">
  <h3><i class="zmdi zmdi-key"></i>{ts}API Key{/ts}</h3>

  <div id="apikey-result-panel" style="display:none" class="crm-connector-result-panel">
    <div class="crm-connector-result-warning">
      <div class="crm-connector-security-notice"><i class="zmdi zmdi-alert-polygon"></i> {ts}Security notice: This API key is sensitive credentials. Do not share it publicly. Store it only in a trusted backend service or server, and keep it confidential.{/ts}</div>
    </div>
    <div id="apikey-result-value" class="crm-connector-result-value"></div>
    <div class="crm-connector-result-actions">
      {ts}This information will not be shown again. Please copy and save it now.{/ts}
      <button id="btn-copy-apikey" class="button crm-button"><i class="zmdi zmdi-link"></i> {ts}Copy{/ts}</button>
      <span id="apikey-copy-confirm" style="display:none" class="crm-connector-copy-confirm">{ts}Copied{/ts}</span>
      <button id="btn-close-apikey" class="button crm-button crm-button-type-main" style="margin-left:16px"><i class="zmdi zmdi-close-circle"></i>{ts}I have copied it, close{/ts}</button>
    </div>
  </div>

  <div id="apikey-action-area">
    {if $apiKeyInfo.has_key}
      <button id="btn-reset-apikey" class="button crm-button crm-button-type-cancel">
        <i class="zmdi zmdi-refresh-sync"></i>{ts}Regenerate{/ts}
      </button>
    {/if}
  </div>

  {if $apiKeyInfo.has_key}
  <table class="crm-info-panel" style="margin-top:16px">
    <tr>
      <td class="label">{ts}API Key (masked){/ts}</td>
      <td><code>{$apiKeyInfo.masked_api_key|escape}</code></td>
    </tr>
    <tr>
      <td class="label">{ts}Site Key{/ts}</td>
      <td>
        <span class="click-to-show">
          <a href="#" class="click-to-show-trigger crm-button">{$apiKeyInfo.masked_site_key|escape} ({ts}Click to show details{/ts})</a>
          <code class="click-to-show-info">{$apiKeyInfo.full_site_key|escape}</code>
        </span>
      </td>
    </tr>
    <tr>
      <td class="label">{ts}Generated Date{/ts}</td>
      <td>{if $apiKeyInfo.generated_date}{$apiKeyInfo.generated_date|crmDate}{else}-{/if}</td>
    </tr>
    <tr>
      <td class="label">{ts}Generated By{/ts}</td>
      <td>{if $apiKeyInfo.generated_by}{$apiKeyInfo.generated_by|escape}{else}-{/if}</td>
    </tr>
    <tr>
      <td class="label">{ts}Last Login{/ts}</td>
      <td>{if $apiKeyInfo.last_login}{$apiKeyInfo.last_login|crmDate}{else}-{/if}</td>
    </tr>
  </table>
  {/if}
</div>
{/if}

</div>{* #crm-connector-page *}

{include file="CRM/common/clickToShow.tpl"}

<style>{literal}
.crm-connector-result-panel {
  border: 2px solid #e8b84b;
  background: #fffbf0;
  border-radius: 4px;
  padding: 16px;
  margin-bottom: 16px;
}
.crm-connector-result-warning {
  font-weight: bold;
  color: #8a6200;
  margin-bottom: 10px;
}
.crm-connector-result-value {
  font-family: monospace;
  word-break: break-all;
  background: #f5f5f5;
  border: 1px solid #ddd;
  border-radius: 3px;
  padding: 10px;
  margin-bottom: 12px;
  font-size: 13px;
}
.crm-connector-result-actions {
  display: flex;
  align-items: center;
}
.crm-connector-copy-confirm {
  color: #2e7d32;
  font-weight: bold;
  margin-left: 8px;
}
.crm-connector-security-notice {
  font-weight: normal;
  color: #9b0202;
  background: #fff3cd;
  border-left: 3px solid #e8a000;
  padding: 5px 8px;
  border-radius: 2px;
}
{/literal}
</style>

<script>
{literal}
cj(document).ready(function($) {
  var cid            = {/literal}{$cid}{literal};
  var urlGenerateMCP = '{/literal}{$ajaxGenerateMCP}{literal}';
  var urlResetMCP    = '{/literal}{$ajaxResetMCP}{literal}';
  var urlGenerateKey = '{/literal}{$ajaxGenerateAPIKey}{literal}';
  var urlResetKey    = '{/literal}{$ajaxResetAPIKey}{literal}';
  var urlRevokeKey   = '{/literal}{$ajaxRevokeKey}{literal}';

  // -----------------------------------------------------------------------
  // Generic AJAX POST helper
  // -----------------------------------------------------------------------
  function doPost(url, onSuccess) {
    $.ajax({
      url: url,
      method: 'POST',
      contentType: 'application/json',
      data: JSON.stringify({ cid: cid }),
      dataType: 'json',
      success: function(resp) {
        if (resp.status === 1) {
          onSuccess(resp);
        }
        else {
          CRM.alert(resp.message || '{/literal}{ts escape='js'}An error occurred. Please try again.{/ts}{literal}', '{/literal}{ts escape='js'}Error{/ts}{literal}', 'error');
        }
      },
      error: function() {
        CRM.alert('{/literal}{ts escape='js'}Request failed. Please try again.{/ts}{literal}', '{/literal}{ts escape='js'}Error{/ts}{literal}', 'error');
      }
    });
  }

  // -----------------------------------------------------------------------
  // Show result panel (inline, show-once)
  // -----------------------------------------------------------------------
  function showResult(panelId, valueId, copyBtnId, confirmId, closeBtnId, actionAreaId, value) {
    $('#' + valueId).text(value);
    $('#' + confirmId).hide();
    $('#' + panelId).show();
    $('#' + actionAreaId).hide();
  }

  // -----------------------------------------------------------------------
  // Copy button handler factory
  // -----------------------------------------------------------------------
  function bindCopy(copyBtnId, valueId, confirmId) {
    $('#' + copyBtnId).on('click', function() {
      var val = $('#' + valueId).text();
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(val).then(function() {
          $('#' + confirmId).show();
        });
      }
      else {
        var $tmp = $('<textarea>').val(val).css({ position: 'fixed', opacity: 0 }).appendTo('body');
        $tmp[0].select();
        document.execCommand('copy');
        $tmp.remove();
        $('#' + confirmId).show();
      }
    });
  }

  // -----------------------------------------------------------------------
  // MCP section
  // -----------------------------------------------------------------------
  bindCopy('btn-copy-mcp', 'mcp-result-value', 'mcp-copy-confirm');

  $('#btn-close-mcp').on('click', function() {
    location.reload();
  });

  $('#btn-generate-mcp').on('click', function() {
    doPost(urlGenerateMCP, function(resp) {
      showResult('mcp-result-panel', 'mcp-result-value', 'btn-copy-mcp', 'mcp-copy-confirm', 'btn-close-mcp', 'mcp-action-area', resp.full_url);
    });
  });

  $('#btn-reset-mcp').on('click', function() {
    if (!confirm('{/literal}{ts escape='js'}Warning: Regenerating will immediately invalidate the existing Connector URL. Any configured MCP clients will need to be reconfigured. Continue?{/ts}{literal}')) {
      return;
    }
    doPost(urlResetMCP, function(resp) {
      showResult('mcp-result-panel', 'mcp-result-value', 'btn-copy-mcp', 'mcp-copy-confirm', 'btn-close-mcp', 'mcp-action-area', resp.full_url);
    });
  });

  $('#btn-revoke-key').on('click', function() {
    if (!confirm('{/literal}{ts escape='js'}Warning: Revoking will immediately disable all MCP and API Key access for this contact. This action cannot be undone. Continue?{/ts}{literal}')) {
      return;
    }
    doPost(urlRevokeKey, function(resp) {
      location.reload();
    });
  });

  // -----------------------------------------------------------------------
  // API Key section
  // -----------------------------------------------------------------------
  bindCopy('btn-copy-apikey', 'apikey-result-value', 'apikey-copy-confirm');

  $('#btn-close-apikey').on('click', function() {
    location.reload();
  });

  $('#btn-generate-apikey').on('click', function() {
    doPost(urlGenerateKey, function(resp) {
      showResult('apikey-result-panel', 'apikey-result-value', 'btn-copy-apikey', 'apikey-copy-confirm', 'btn-close-apikey', 'apikey-action-area', resp.api_key);
    });
  });

  $('#btn-reset-apikey').on('click', function() {
    if (!confirm('{/literal}{ts escape='js'}Warning: Resetting will immediately invalidate the existing API Key. Continue?{/ts}{literal}')) {
      return;
    }
    doPost(urlResetKey, function(resp) {
      showResult('apikey-result-panel', 'apikey-result-value', 'btn-copy-apikey', 'apikey-copy-confirm', 'btn-close-apikey', 'apikey-action-area', resp.api_key);
    });
  });

});
{/literal}
</script>
