<?php
global $menu_links;
$menu_links['navigation'] = array (
  0 => 
  array (
    'path' => 'batch',
    'query' => NULL,
    'title' => '',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  1 => 
  array (
    'path' => 'node',
    'query' => NULL,
    'title' => 'Content',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  2 => 
  array (
    'path' => 'logout',
    'query' => NULL,
    'title' => 'Log out',
    'menu' => 'navigation',
    'weight' => '-42',
    'module' => 'menu',
    'hidden' => '0',
  ),
  3 => 
  array (
    'path' => 'rss.xml',
    'query' => NULL,
    'title' => 'RSS feed',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  4 => 
  array (
    'path' => 'user',
    'query' => NULL,
    'title' => 'User account',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  5 => 
  array (
    'path' => 'node/%',
    'query' => NULL,
    'title' => '',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  6 => 
  array (
    'path' => 'filter/tips',
    'query' => NULL,
    'title' => 'Compose tips',
    'menu' => 'navigation',
    'weight' => '-48',
    'module' => 'menu',
    'hidden' => '1',
  ),
  7 => 
  array (
    'path' => 'system/files',
    'query' => NULL,
    'title' => 'File download',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  8 => 
  array (
    'path' => 'user/autocomplete',
    'query' => NULL,
    'title' => 'User autocomplete',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  9 => 
  array (
    'path' => 'user/%',
    'query' => NULL,
    'title' => 'My account',
    'menu' => 'navigation',
    'weight' => '-47',
    'module' => 'menu',
    'hidden' => '0',
    'children' => 
    array (
      0 => 
      array (
        'path' => 'user/%/delete',
        'query' => NULL,
        'title' => 'Delete',
        'menu' => 'navigation',
        'weight' => '0',
        'module' => 'menu',
        'hidden' => '-1',
      ),
    ),
  ),
  10 => 
  array (
    'path' => 'node/%/delete',
    'query' => NULL,
    'title' => 'Delete',
    'menu' => 'navigation',
    'weight' => '1',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  11 => 
  array (
    'path' => 'admin/build/menu-customize/%/delete',
    'query' => NULL,
    'title' => 'Delete menu',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  12 => 
  array (
    'path' => 'user/reset/%/%/%',
    'query' => NULL,
    'title' => 'Reset password',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  13 => 
  array (
    'path' => 'node/%/revisions/%/delete',
    'query' => NULL,
    'title' => 'Delete earlier revision',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  14 => 
  array (
    'path' => 'node/%/revisions/%/revert',
    'query' => NULL,
    'title' => 'Revert to earlier revision',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  15 => 
  array (
    'path' => 'node/%/revisions/%/view',
    'query' => NULL,
    'title' => 'Revisions',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  16 => 
  array (
    'path' => 'imce',
    'query' => NULL,
    'title' => 'File browser',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  17 => 
  array (
    'path' => 'l10n_client/save',
    'query' => NULL,
    'title' => 'Save string',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  18 => 
  array (
    'path' => 'locale',
    'query' => NULL,
    'title' => 'Translate strings',
    'menu' => 'navigation',
    'weight' => '-49',
    'module' => 'menu',
    'hidden' => '1',
  ),
  19 => 
  array (
    'path' => 'toboggan/denied',
    'query' => NULL,
    'title' => 'Access denied',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  20 => 
  array (
    'path' => 'taxonomy/autocomplete',
    'query' => NULL,
    'title' => 'Autocomplete taxonomy',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  21 => 
  array (
    'path' => 'toboggan/revalidate/%',
    'query' => NULL,
    'title' => 'Re-send validation e-mail',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  22 => 
  array (
    'path' => 'taxonomy/term/%',
    'query' => NULL,
    'title' => 'Taxonomy term',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  23 => 
  array (
    'path' => 'user/validate/%/%/%',
    'query' => NULL,
    'title' => 'Validate e-mail address',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  24 => 
  array (
    'path' => 'admin/content/node-type/page/delete',
    'query' => NULL,
    'title' => 'Delete',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  25 => 
  array (
    'path' => 'civicrm',
    'query' => NULL,
    'title' => 'CiviCRM',
    'menu' => 'navigation',
    'weight' => '0',
    'module' => 'menu',
    'hidden' => '-1',
  ),
  26 => 
  array (
    'path' => 'civicrm/dashboard',
    'query' => NULL,
    'title' => 'CiviCRM',
    'menu' => 'navigation',
    'weight' => '-50',
    'module' => 'menu',
    'hidden' => '1',
  ),
  27 => 
  array (
    'path' => 'http://netivism.com.tw/support',
    'query' => NULL,
    'title' => '說明',
    'menu' => 'navigation',
    'weight' => '-44',
    'module' => 'menu',
    'hidden' => '0',
  ),
  28 => 
  array (
    'path' => 'user/login',
    'query' => NULL,
    'title' => '登入',
    'menu' => 'navigation',
    'weight' => '-43',
    'module' => 'menu',
    'hidden' => '0',
  ),
  29 => 
  array (
    'path' => 'admin',
    'query' => NULL,
    'title' => '網站管理',
    'menu' => 'navigation',
    'weight' => '-45',
    'module' => 'menu',
    'hidden' => '0',
    'children' => 
    array (
      0 => 
      array (
        'path' => 'admin/compact',
        'query' => NULL,
        'title' => 'Compact mode',
        'menu' => 'navigation',
        'weight' => '0',
        'module' => 'menu',
        'hidden' => '-1',
      ),
      1 => 
      array (
        'path' => 'admin/content',
        'query' => NULL,
        'title' => 'Content management',
        'menu' => 'navigation',
        'weight' => '-10',
        'module' => 'menu',
        'hidden' => '0',
        'children' => 
        array (
          0 => 
          array (
            'path' => 'admin/content/node',
            'query' => NULL,
            'title' => 'Content',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
          ),
          1 => 
          array (
            'path' => 'admin/content/types',
            'query' => NULL,
            'title' => 'Content types',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          2 => 
          array (
            'path' => 'admin/content/node-settings',
            'query' => NULL,
            'title' => 'Post settings',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/content/node-settings/rebuild',
                'query' => NULL,
                'title' => 'Rebuild permissions',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          3 => 
          array (
            'path' => 'admin/content/rss-publishing',
            'query' => NULL,
            'title' => 'RSS publishing',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          4 => 
          array (
            'path' => 'admin/content/taxonomy',
            'query' => NULL,
            'title' => 'Taxonomy',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/content/taxonomy/%',
                'query' => NULL,
                'title' => 'List terms',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/content/taxonomy/edit/term',
                'query' => NULL,
                'title' => 'Edit term',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              2 => 
              array (
                'path' => 'admin/content/taxonomy/edit/vocabulary/%',
                'query' => NULL,
                'title' => 'Edit vocabulary',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          5 => 
          array (
            'path' => 'admin/content/node-type/page',
            'query' => NULL,
            'title' => '頁面',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '-1',
          ),
        ),
      ),
      2 => 
      array (
        'path' => 'admin/reports',
        'query' => NULL,
        'title' => 'Reports',
        'menu' => 'navigation',
        'weight' => '5',
        'module' => 'menu',
        'hidden' => '0',
        'children' => 
        array (
          0 => 
          array (
            'path' => 'admin/reports/status',
            'query' => NULL,
            'title' => 'Status report',
            'menu' => 'navigation',
            'weight' => '10',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/reports/status/php',
                'query' => NULL,
                'title' => 'PHP',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/reports/status/run-cron',
                'query' => NULL,
                'title' => 'Run cron',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              2 => 
              array (
                'path' => 'admin/reports/status/sql',
                'query' => NULL,
                'title' => 'SQL',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          1 => 
          array (
            'path' => 'admin/reports/dblog',
            'query' => NULL,
            'title' => 'Recent log entries',
            'menu' => 'navigation',
            'weight' => '-1',
            'module' => 'menu',
            'hidden' => '0',
          ),
          2 => 
          array (
            'path' => 'admin/reports/access-denied',
            'query' => NULL,
            'title' => 'Top \'access denied\' errors',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          3 => 
          array (
            'path' => 'admin/reports/page-not-found',
            'query' => NULL,
            'title' => 'Top \'page not found\' errors',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          4 => 
          array (
            'path' => 'admin/reports/event/%',
            'query' => NULL,
            'title' => 'Details',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '-1',
          ),
        ),
      ),
      3 => 
      array (
        'path' => 'admin/build',
        'query' => NULL,
        'title' => 'Site building',
        'menu' => 'navigation',
        'weight' => '-10',
        'module' => 'menu',
        'hidden' => '0',
        'children' => 
        array (
          0 => 
          array (
            'path' => 'admin/build/block',
            'query' => NULL,
            'title' => 'Blocks',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/build/block/configure',
                'query' => NULL,
                'title' => 'Configure block',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/build/block/delete',
                'query' => NULL,
                'title' => 'Delete block',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              2 => 
              array (
                'path' => 'admin/build/block/list/js',
                'query' => NULL,
                'title' => 'JavaScript List Form',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          1 => 
          array (
            'path' => 'admin/build/modules',
            'query' => NULL,
            'title' => 'Modules',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/build/modules/list/confirm',
                'query' => NULL,
                'title' => 'List',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/build/modules/uninstall/confirm',
                'query' => NULL,
                'title' => 'Uninstall',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          2 => 
          array (
            'path' => 'admin/build/themes',
            'query' => NULL,
            'title' => 'Themes',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          3 => 
          array (
            'path' => 'admin/build/menu-customize/%',
            'query' => NULL,
            'title' => 'Customize menu',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '-1',
          ),
          4 => 
          array (
            'path' => 'admin/build/translate',
            'query' => NULL,
            'title' => 'Translate interface',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/build/translate/delete/%',
                'query' => NULL,
                'title' => 'Delete string',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/build/translate/edit/%',
                'query' => NULL,
                'title' => 'Edit string',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          5 => 
          array (
            'path' => 'admin/build/path',
            'query' => NULL,
            'title' => 'URL aliases',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/build/path/delete',
                'query' => NULL,
                'title' => 'Delete alias',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/build/path/edit',
                'query' => NULL,
                'title' => 'Edit alias',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          6 => 
          array (
            'path' => 'admin/build/menu',
            'query' => NULL,
            'title' => 'Menus',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/build/menu/item/%/delete',
                'query' => NULL,
                'title' => 'Delete menu item',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/build/menu/item/%/edit',
                'query' => NULL,
                'title' => 'Edit menu item',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              2 => 
              array (
                'path' => 'admin/build/menu/item/%/reset',
                'query' => NULL,
                'title' => 'Reset menu item',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              3 => 
              array (
                'path' => 'admin/build/menu-customize/navigation',
                'query' => NULL,
                'title' => '導覽',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '0',
              ),
              4 => 
              array (
                'path' => 'admin/build/menu-customize/primary-links',
                'query' => NULL,
                'title' => '主選單',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '0',
              ),
              5 => 
              array (
                'path' => 'admin/build/menu-customize/secondary-links',
                'query' => NULL,
                'title' => '次選單',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '0',
              ),
              6 => 
              array (
                'path' => 'admin/build/menu-customize/menu-search',
                'query' => NULL,
                'title' => '搜尋選單',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '0',
              ),
              7 => 
              array (
                'path' => 'admin/build/menu-customize/menu-footer',
                'query' => NULL,
                'title' => '底部導覽',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '0',
              ),
            ),
          ),
          7 => 
          array (
            'path' => 'civicrm/admin',
            'query' => NULL,
            'title' => '支持者系統管理',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'civicrm/admin',
                'query' => NULL,
                'title' => '設定',
                'menu' => 'navigation',
                'weight' => '-50',
                'module' => 'menu',
                'hidden' => '0',
                'children' => 
                array (
                  0 => 
                  array (
                    'path' => 'civicrm/admin/configtask',
                    'query' => 'reset=1',
                    'title' => '系統設定檢查表',
                    'menu' => 'navigation',
                    'weight' => '1',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  1 => 
                  array (
                    'path' => 'civicrm/admin/mapping',
                    'query' => 'reset=1',
                    'title' => '匯入/匯出對應',
                    'menu' => 'navigation',
                    'weight' => '3',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  2 => 
                  array (
                    'path' => 'civicrm/admin/messageTemplates',
                    'query' => 'reset=1',
                    'title' => '訊息範本',
                    'menu' => 'navigation',
                    'weight' => '4',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  3 => 
                  array (
                    'path' => 'civicrm/admin/domain',
                    'query' => 'action=update&reset=1',
                    'title' => '網域資訊頁',
                    'menu' => 'navigation',
                    'weight' => '5',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  4 => 
                  array (
                    'path' => 'civicrm/admin/options/from_email_address',
                    'query' => 'group=from_email_address&reset=1',
                    'title' => 'Email 寄件者',
                    'menu' => 'navigation',
                    'weight' => '6',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  5 => 
                  array (
                    'path' => 'civicrm/admin/setting/updateConfigBackend',
                    'query' => 'reset=1',
                    'title' => '更新目錄路徑和網址',
                    'menu' => 'navigation',
                    'weight' => '7',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  6 => 
                  array (
                    'path' => 'civicrm/admin/setting',
                    'query' => 'reset=1',
                    'title' => '全域設定',
                    'menu' => 'navigation',
                    'weight' => '2',
                    'module' => 'menu',
                    'hidden' => '0',
                    'children' => 
                    array (
                      0 => 
                      array (
                        'path' => 'civicrm/admin/setting/component',
                        'query' => 'reset=1',
                        'title' => '啟用的 CiviCRM 模組',
                        'menu' => 'navigation',
                        'weight' => '1',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      1 => 
                      array (
                        'path' => 'civicrm/admin/setting/preferences/display',
                        'query' => 'reset=1',
                        'title' => '網站設定（屏幕和表格配置）',
                        'menu' => 'navigation',
                        'weight' => '2',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      2 => 
                      array (
                        'path' => 'civicrm/admin/setting/path',
                        'query' => 'reset=1',
                        'title' => '資料夾',
                        'menu' => 'navigation',
                        'weight' => '3',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      3 => 
                      array (
                        'path' => 'civicrm/admin/setting/url',
                        'query' => 'reset=1',
                        'title' => '版型資源路徑',
                        'menu' => 'navigation',
                        'weight' => '4',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      4 => 
                      array (
                        'path' => 'civicrm/admin/setting/smtp',
                        'query' => 'reset=1',
                        'title' => '外寄 Email（SMTP/Sendmail）',
                        'menu' => 'navigation',
                        'weight' => '5',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      5 => 
                      array (
                        'path' => 'civicrm/admin/setting/mapping',
                        'query' => 'reset=1',
                        'title' => '地圖與經緯度對應',
                        'menu' => 'navigation',
                        'weight' => '6',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      6 => 
                      array (
                        'path' => 'civicrm/admin/paymentProcessor',
                        'query' => 'reset=1',
                        'title' => '金流機制',
                        'menu' => 'navigation',
                        'weight' => '7',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      7 => 
                      array (
                        'path' => 'civicrm/admin/setting/localization',
                        'query' => 'reset=1',
                        'title' => '地區及語系',
                        'menu' => 'navigation',
                        'weight' => '8',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      8 => 
                      array (
                        'path' => 'civicrm/admin/setting/preferences/address',
                        'query' => 'reset=1',
                        'title' => '地址格式設定',
                        'menu' => 'navigation',
                        'weight' => '9',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      9 => 
                      array (
                        'path' => 'civicrm/admin/setting/search',
                        'query' => 'reset=1',
                        'title' => '搜尋設定',
                        'menu' => 'navigation',
                        'weight' => '10',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      10 => 
                      array (
                        'path' => 'civicrm/admin/setting/date',
                        'query' => 'reset=1',
                        'title' => '日期格式',
                        'menu' => 'navigation',
                        'weight' => '11',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      11 => 
                      array (
                        'path' => 'civicrm/admin/setting/uf',
                        'query' => 'reset=1',
                        'title' => 'CMS 整合',
                        'menu' => 'navigation',
                        'weight' => '12',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      12 => 
                      array (
                        'path' => 'civicrm/admin/setting/misc',
                        'query' => 'reset=1',
                        'title' => '雜項（版本檢查，reCAPTCHA 驗證服務...）',
                        'menu' => 'navigation',
                        'weight' => '13',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      13 => 
                      array (
                        'path' => 'civicrm/admin/options/safe_file_extension',
                        'query' => 'group=safe_file_extension&reset=1',
                        'title' => '安全及檔案副檔名',
                        'menu' => 'navigation',
                        'weight' => '14',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                      14 => 
                      array (
                        'path' => 'civicrm/admin/setting/debug',
                        'query' => 'reset=1',
                        'title' => '除錯',
                        'menu' => 'navigation',
                        'weight' => '15',
                        'module' => 'menu',
                        'hidden' => '0',
                      ),
                    ),
                  ),
                ),
              ),
              1 => 
              array (
                'path' => 'civicrm/admin',
                'query' => NULL,
                'title' => '自訂',
                'menu' => 'navigation',
                'weight' => '5',
                'module' => 'menu',
                'hidden' => '0',
                'children' => 
                array (
                  0 => 
                  array (
                    'path' => 'civicrm/admin/custom/group',
                    'query' => 'reset=1',
                    'title' => '自訂欄位',
                    'menu' => 'navigation',
                    'weight' => '-50',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  1 => 
                  array (
                    'path' => 'civicrm/admin/uf/group',
                    'query' => 'reset=1',
                    'title' => '資料表單',
                    'menu' => 'navigation',
                    'weight' => '-49',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  2 => 
                  array (
                    'path' => 'civicrm/admin/price',
                    'query' => 'reset=1',
                    'title' => '價格設定',
                    'menu' => 'navigation',
                    'weight' => '-48',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  3 => 
                  array (
                    'path' => 'civicrm/admin/options/activity_type',
                    'query' => 'reset=1&group=activity_type',
                    'title' => '動態類型',
                    'menu' => 'navigation',
                    'weight' => '-47',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  4 => 
                  array (
                    'path' => 'civicrm/admin/tag',
                    'query' => 'reset=1',
                    'title' => 'Tag（種類）',
                    'menu' => 'navigation',
                    'weight' => '-46',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  5 => 
                  array (
                    'path' => 'civicrm/admin/options/gender',
                    'query' => 'reset=1&group=gender',
                    'title' => '性別選項',
                    'menu' => 'navigation',
                    'weight' => '-45',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  6 => 
                  array (
                    'path' => 'civicrm/admin/options/individual_prefix',
                    'query' => 'group=individual_prefix&reset=1',
                    'title' => '個人稱銜(女士、先生…)',
                    'menu' => 'navigation',
                    'weight' => '-44',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  7 => 
                  array (
                    'path' => 'civicrm/admin/options/individual_suffix',
                    'query' => 'group=individual_suffix&reset=1',
                    'title' => '個人稱呼字尾(Jr, Sr...)',
                    'menu' => 'navigation',
                    'weight' => '-43',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  8 => 
                  array (
                    'path' => 'civicrm/admin/options/addressee',
                    'query' => 'group=addressee&reset=1',
                    'title' => '地址格式',
                    'menu' => 'navigation',
                    'weight' => '-42',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  9 => 
                  array (
                    'path' => 'civicrm/admin/options/email_greeting',
                    'query' => 'group=email_greeting&reset=1',
                    'title' => 'Email問候語',
                    'menu' => 'navigation',
                    'weight' => '-41',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  10 => 
                  array (
                    'path' => 'civicrm/admin/options/postal_greeting',
                    'query' => 'group=postal_greeting&reset=1',
                    'title' => '信件問候',
                    'menu' => 'navigation',
                    'weight' => '-40',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  11 => 
                  array (
                    'path' => 'civicrm/admin/options/instant_messenger_service',
                    'query' => 'group=instant_messenger_service&reset=1',
                    'title' => '即時通訊服務',
                    'menu' => 'navigation',
                    'weight' => '-39',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  12 => 
                  array (
                    'path' => 'civicrm/admin/locationType',
                    'query' => 'reset=1',
                    'title' => '地點類型（住家、工作場所）',
                    'menu' => 'navigation',
                    'weight' => '-38',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  13 => 
                  array (
                    'path' => 'civicrm/admin/options/mobile_provider',
                    'query' => 'group=mobile_provider&reset=1',
                    'title' => '電信業者',
                    'menu' => 'navigation',
                    'weight' => '-37',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  14 => 
                  array (
                    'path' => 'civicrm/admin/options/phone_type',
                    'query' => 'group=phone_type&reset=1',
                    'title' => '電話類型',
                    'menu' => 'navigation',
                    'weight' => '-36',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  15 => 
                  array (
                    'path' => 'civicrm/admin/options/website_type',
                    'query' => 'group=website_type&reset=1',
                    'title' => '網站類型',
                    'menu' => 'navigation',
                    'weight' => '-35',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  16 => 
                  array (
                    'path' => 'civicrm/admin/options/preferred_communication_method',
                    'query' => 'group=preferred_communication_method&reset=1',
                    'title' => '偏好聯絡方式',
                    'menu' => 'navigation',
                    'weight' => '-34',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  17 => 
                  array (
                    'path' => 'civicrm/admin/options/subtype',
                    'query' => 'reset=1',
                    'title' => '聯絡人類型',
                    'menu' => 'navigation',
                    'weight' => '-33',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                  18 => 
                  array (
                    'path' => 'civicrm/admin/options/wordreplacements',
                    'query' => 'reset=1',
                    'title' => '置換',
                    'menu' => 'navigation',
                    'weight' => '-32',
                    'module' => 'menu',
                    'hidden' => '0',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      4 => 
      array (
        'path' => 'admin/settings',
        'query' => NULL,
        'title' => 'Site configuration',
        'menu' => 'navigation',
        'weight' => '-5',
        'module' => 'menu',
        'hidden' => '0',
        'children' => 
        array (
          0 => 
          array (
            'path' => 'admin/settings/actions',
            'query' => NULL,
            'title' => 'Actions',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/settings/actions/configure',
                'query' => NULL,
                'title' => 'Configure an advanced action',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/settings/actions/orphan',
                'query' => NULL,
                'title' => 'Remove orphans',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              2 => 
              array (
                'path' => 'admin/settings/actions/delete/%',
                'query' => NULL,
                'title' => 'Delete action',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          1 => 
          array (
            'path' => 'admin/settings/admin',
            'query' => NULL,
            'title' => 'Administration theme',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          2 => 
          array (
            'path' => 'admin/settings/clean-urls',
            'query' => NULL,
            'title' => 'Clean URLs',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/settings/clean-urls/check',
                'query' => NULL,
                'title' => 'Clean URL check',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          3 => 
          array (
            'path' => 'admin/settings/date-time',
            'query' => NULL,
            'title' => 'Date and time',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/settings/date-time/lookup',
                'query' => NULL,
                'title' => 'Date and time lookup',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          4 => 
          array (
            'path' => 'admin/settings/error-reporting',
            'query' => NULL,
            'title' => 'Error reporting',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          5 => 
          array (
            'path' => 'admin/settings/file-system',
            'query' => NULL,
            'title' => 'File system',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          6 => 
          array (
            'path' => 'admin/settings/image-toolkit',
            'query' => NULL,
            'title' => 'Image toolkit',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          7 => 
          array (
            'path' => 'admin/settings/filters',
            'query' => NULL,
            'title' => 'Input formats',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/settings/filters/%',
                'query' => NULL,
                'title' => '',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/settings/filters/delete',
                'query' => NULL,
                'title' => 'Delete input format',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          8 => 
          array (
            'path' => 'admin/settings/logging',
            'query' => NULL,
            'title' => 'Logging and alerts',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/settings/logging/dblog',
                'query' => NULL,
                'title' => 'Database logging',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '1',
              ),
            ),
          ),
          9 => 
          array (
            'path' => 'admin/settings/performance',
            'query' => NULL,
            'title' => 'Performance',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          10 => 
          array (
            'path' => 'admin/settings/site-information',
            'query' => NULL,
            'title' => 'Site information',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
          ),
          11 => 
          array (
            'path' => 'admin/settings/site-maintenance',
            'query' => NULL,
            'title' => 'Site maintenance',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
          ),
          12 => 
          array (
            'path' => 'admin/settings/imce',
            'query' => NULL,
            'title' => 'IMCE',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/settings/imce/profile',
                'query' => NULL,
                'title' => 'Add new profile',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          13 => 
          array (
            'path' => 'admin/settings/language',
            'query' => NULL,
            'title' => 'Languages',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/settings/language/delete/%',
                'query' => NULL,
                'title' => 'Confirm',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/settings/language/edit/%',
                'query' => NULL,
                'title' => 'Edit language',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          14 => 
          array (
            'path' => 'admin/settings/localefix',
            'query' => NULL,
            'title' => 'Localefix Configuration',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          15 => 
          array (
            'path' => 'admin/settings/civicrm_import_group_tag',
            'query' => NULL,
            'title' => 'Import Group and Tag into CiviCRM',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          16 => 
          array (
            'path' => 'admin/settings/pdf_receipts',
            'query' => NULL,
            'title' => 'CiviCRM PDF Receipts',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
          ),
          17 => 
          array (
            'path' => 'admin/settings/devel',
            'query' => NULL,
            'title' => 'Devel settings',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
        ),
      ),
      5 => 
      array (
        'path' => 'admin/user',
        'query' => NULL,
        'title' => 'User management',
        'menu' => 'navigation',
        'weight' => '0',
        'module' => 'menu',
        'hidden' => '0',
        'children' => 
        array (
          0 => 
          array (
            'path' => 'admin/user/rules',
            'query' => NULL,
            'title' => 'Access rules',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/user/rules/delete',
                'query' => NULL,
                'title' => 'Delete rule',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
              1 => 
              array (
                'path' => 'admin/user/rules/edit',
                'query' => NULL,
                'title' => 'Edit rule',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          1 => 
          array (
            'path' => 'admin/user/permissions',
            'query' => NULL,
            'title' => 'Permissions',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
          ),
          2 => 
          array (
            'path' => 'admin/user/roles',
            'query' => NULL,
            'title' => 'Roles',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
            'children' => 
            array (
              0 => 
              array (
                'path' => 'admin/user/roles/edit',
                'query' => NULL,
                'title' => 'Edit role',
                'menu' => 'navigation',
                'weight' => '0',
                'module' => 'menu',
                'hidden' => '-1',
              ),
            ),
          ),
          3 => 
          array (
            'path' => 'admin/user/settings',
            'query' => NULL,
            'title' => 'User settings',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          4 => 
          array (
            'path' => 'admin/user/user',
            'query' => NULL,
            'title' => 'Users',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '0',
          ),
          5 => 
          array (
            'path' => 'admin/user/logintoboggan',
            'query' => NULL,
            'title' => 'LoginToboggan',
            'menu' => 'navigation',
            'weight' => '0',
            'module' => 'menu',
            'hidden' => '1',
          ),
          6 => 
          array (
            'path' => 'civicrm/admin/access',
            'query' => 'reset=1',
            'title' => '存取控制',
            'menu' => 'navigation',
            'weight' => '1',
            'module' => 'menu',
            'hidden' => '0',
          ),
          7 => 
          array (
            'path' => 'civicrm/admin/synchUser',
            'query' => 'reset=1',
            'title' => '同步使用者到聯絡人',
            'menu' => 'navigation',
            'weight' => '2',
            'module' => 'menu',
            'hidden' => '0',
          ),
        ),
      ),
    ),
  ),
  30 => 
  array (
    'path' => 'node/add',
    'query' => NULL,
    'title' => 'Create content',
    'menu' => 'navigation',
    'weight' => '-46',
    'module' => 'menu',
    'hidden' => '0',
    'children' => 
    array (
      0 => 
      array (
        'path' => 'node/add/page',
        'query' => NULL,
        'title' => '頁面',
        'menu' => 'navigation',
        'weight' => '0',
        'module' => 'menu',
        'hidden' => '0',
      ),
    ),
  ),
);

$menu_links['primary-links'] =array (
  0 => 
  array (
    'path' => 'civicrm/contact/search',
    'query' => 'reset=1',
    'title' => '聯絡人',
    'menu' => 'primary-links',
    'weight' => '-49',
    'module' => 'menu',
    'hidden' => '0',
    'expanded' => 1,
    'children' => 
    array (
      0 => 
      array (
        'path' => 'civicrm/contact/add',
        'query' => 'reset=1&ct=Household',
        'title' => '新增家庭',
        'menu' => 'primary-links',
        'weight' => '-49',
        'module' => 'menu',
        'hidden' => '0',
      ),
      1 => 
      array (
        'path' => 'civicrm/contact/add',
        'query' => 'reset=1&ct=Individual',
        'title' => '新增個人',
        'menu' => 'primary-links',
        'weight' => '-50',
        'module' => 'menu',
        'hidden' => '0',
      ),
      2 => 
      array (
        'path' => 'civicrm/contact/add',
        'query' => 'reset=1&ct=Organization',
        'title' => '新增組織',
        'menu' => 'primary-links',
        'weight' => '-48',
        'module' => 'menu',
        'hidden' => '0',
      ),
      3 => 
      array (
        'path' => 'civicrm/activity',
        'query' => 'reset=1&action=add&context=standalone',
        'title' => '新增動態',
        'menu' => 'primary-links',
        'weight' => '-47',
        'module' => 'menu',
        'hidden' => '0',
      ),
      4 => 
      array (
        'path' => 'civicrm/activity/add',
        'query' => 'atype=3&action=add&reset=1&context=standalone',
        'title' => '新增 Email',
        'menu' => 'primary-links',
        'weight' => '-46',
        'module' => 'menu',
        'hidden' => '0',
      ),
      5 => 
      array (
        'path' => 'civicrm/import/contact',
        'query' => 'reset=1',
        'title' => '匯入聯絡人資料',
        'menu' => 'primary-links',
        'weight' => '-45',
        'module' => 'menu',
        'hidden' => '0',
      ),
      6 => 
      array (
        'path' => 'civicrm/import/activity',
        'query' => 'reset=1',
        'title' => '匯入動態記錄',
        'menu' => 'primary-links',
        'weight' => '-44',
        'module' => 'menu',
        'hidden' => '0',
      ),
      7 => 
      array (
        'path' => 'civicrm/group/add',
        'query' => 'reset=1',
        'title' => '新增群組',
        'menu' => 'primary-links',
        'weight' => '-43',
        'module' => 'menu',
        'hidden' => '0',
      ),
      8 => 
      array (
        'path' => 'civicrm/group',
        'query' => 'reset=1',
        'title' => '管理群組',
        'menu' => 'primary-links',
        'weight' => '-42',
        'module' => 'menu',
        'hidden' => '0',
      ),
      9 => 
      array (
        'path' => 'civicrm/admin/tag',
        'query' => 'reset=1&action=add',
        'title' => '新增Tag',
        'menu' => 'primary-links',
        'weight' => '-41',
        'module' => 'menu',
        'hidden' => '0',
      ),
      10 => 
      array (
        'path' => 'civicrm/admin/tag',
        'query' => 'reset=1',
        'title' => '管理標籤（分類）',
        'menu' => 'primary-links',
        'weight' => '-40',
        'module' => 'menu',
        'hidden' => '0',
      ),
      11 => 
      array (
        'path' => 'civicrm/contact/deduperules',
        'query' => 'reset=1',
        'title' => '搜尋並合併重複的聯絡人',
        'menu' => 'primary-links',
        'weight' => '-38',
        'module' => 'menu',
        'hidden' => '0',
      ),
      12 => 
      array (
        'path' => 'civicrm/admin/reltype',
        'query' => 'reset=1',
        'title' => '新增/管理關係類型',
        'menu' => 'primary-links',
        'weight' => '-39',
        'module' => 'menu',
        'hidden' => '0',
      ),
    ),
  ),
  1 => 
  array (
    'path' => 'civicrm/contribute',
    'query' => 'reset=1',
    'title' => '捐款',
    'menu' => 'primary-links',
    'weight' => '-48',
    'module' => 'menu',
    'hidden' => '0',
    'expanded' => 1,
    'children' => 
    array (
      0 => 
      array (
        'path' => 'civicrm/admin/options/payment_instrument',
        'query' => 'group=payment_instrument&reset=1',
        'title' => '新增/管理付款工具',
        'menu' => 'primary-links',
        'weight' => '-36',
        'module' => 'menu',
        'hidden' => '0',
      ),
      1 => 
      array (
        'path' => 'civicrm/contribute/add',
        'query' => 'reset=1&action=add&context=standalone',
        'title' => '新增捐款',
        'menu' => 'primary-links',
        'weight' => '-50',
        'module' => 'menu',
        'hidden' => '0',
      ),
      2 => 
      array (
        'path' => 'civicrm/contribute/search',
        'query' => 'reset=1',
        'title' => '搜尋捐款',
        'menu' => 'primary-links',
        'weight' => '-49',
        'module' => 'menu',
        'hidden' => '0',
      ),
      3 => 
      array (
        'path' => 'civicrm/contribute/import',
        'query' => 'reset=1',
        'title' => '匯入捐款資料',
        'menu' => 'primary-links',
        'weight' => '-48',
        'module' => 'menu',
        'hidden' => '0',
      ),
      4 => 
      array (
        'path' => 'civicrm/pledge',
        'query' => 'reset=1',
        'title' => '認捐總覽',
        'menu' => 'primary-links',
        'weight' => '-47',
        'module' => 'menu',
        'hidden' => '0',
      ),
      5 => 
      array (
        'path' => 'civicrm/pledge/add',
        'query' => 'reset=1&action=add&context=standalone',
        'title' => '新增認捐',
        'menu' => 'primary-links',
        'weight' => '-46',
        'module' => 'menu',
        'hidden' => '0',
      ),
      6 => 
      array (
        'path' => 'civicrm/pledge/search',
        'query' => 'reset=1',
        'title' => '搜尋認捐',
        'menu' => 'primary-links',
        'weight' => '-45',
        'module' => 'menu',
        'hidden' => '0',
      ),
      7 => 
      array (
        'path' => 'civicrm/admin/contribute/add',
        'query' => 'reset=1&action=add',
        'title' => '新增募款頁',
        'menu' => 'primary-links',
        'weight' => '-43',
        'module' => 'menu',
        'hidden' => '0',
      ),
      8 => 
      array (
        'path' => 'civicrm/admin/contribute',
        'query' => 'reset=1',
        'title' => '管理募款頁',
        'menu' => 'primary-links',
        'weight' => '-42',
        'module' => 'menu',
        'hidden' => '0',
      ),
      9 => 
      array (
        'path' => 'civicrm/admin/pcp',
        'query' => 'reset=1',
        'title' => '個人募款頁',
        'menu' => 'primary-links',
        'weight' => '-41',
        'module' => 'menu',
        'hidden' => '0',
      ),
      10 => 
      array (
        'path' => 'civicrm/admin/contribute/managePremiums',
        'query' => 'reset=1',
        'title' => '感謝禮 (感謝禮品)',
        'menu' => 'primary-links',
        'weight' => '-40',
        'module' => 'menu',
        'hidden' => '0',
      ),
      11 => 
      array (
        'path' => 'civicrm/admin/price',
        'query' => 'reset=1&action=add',
        'title' => '新增價格表',
        'menu' => 'primary-links',
        'weight' => '-39',
        'module' => 'menu',
        'hidden' => '0',
      ),
      12 => 
      array (
        'path' => 'civicrm/admin/price',
        'query' => 'reset=1',
        'title' => '管理價格表',
        'menu' => 'primary-links',
        'weight' => '-38',
        'module' => 'menu',
        'hidden' => '0',
      ),
      13 => 
      array (
        'path' => 'civicrm/admin/contribute/contributionType',
        'query' => 'reset=1',
        'title' => '新增/管理捐款類型',
        'menu' => 'primary-links',
        'weight' => '-37',
        'module' => 'menu',
        'hidden' => '0',
      ),
      14 => 
      array (
        'path' => 'civicrm/admin/options/accept_creditcard',
        'query' => 'group=accept_creditcard&reset=1',
        'title' => '新增/管理可用的信用卡',
        'menu' => 'primary-links',
        'weight' => '-35',
        'module' => 'menu',
        'hidden' => '0',
      ),
    ),
  ),
  2 => 
  array (
    'path' => 'civicrm/event',
    'query' => 'reset=1',
    'title' => '活動',
    'menu' => 'primary-links',
    'weight' => '-47',
    'module' => 'menu',
    'hidden' => '0',
    'expanded' => 1,
    'children' => 
    array (
      0 => 
      array (
        'path' => 'civicrm/admin/options/participant_listing',
        'query' => 'group=participant_listing&reset=1',
        'title' => '參加者列表範本',
        'menu' => 'primary-links',
        'weight' => '-42',
        'module' => 'menu',
        'hidden' => '0',
      ),
      1 => 
      array (
        'path' => 'civicrm/admin/options/event_type',
        'query' => 'group=event_type&reset=1',
        'title' => '新增/管理活動類型',
        'menu' => 'primary-links',
        'weight' => '-41',
        'module' => 'menu',
        'hidden' => '0',
      ),
      2 => 
      array (
        'path' => 'civicrm/admin/participant_status',
        'query' => 'reset=1',
        'title' => '新增/管理參加者狀態',
        'menu' => 'primary-links',
        'weight' => '-40',
        'module' => 'menu',
        'hidden' => '0',
      ),
      3 => 
      array (
        'path' => 'civicrm/admin/options/participant_role',
        'query' => 'group=participant_role&reset=1',
        'title' => '新增/管理參加者角色',
        'menu' => 'primary-links',
        'weight' => '-39',
        'module' => 'menu',
        'hidden' => '0',
      ),
      4 => 
      array (
        'path' => 'civicrm/participant/add',
        'query' => 'reset=1&action=add&context=standalone',
        'title' => '登記活動參加者',
        'menu' => 'primary-links',
        'weight' => '-50',
        'module' => 'menu',
        'hidden' => '0',
      ),
      5 => 
      array (
        'path' => 'civicrm/event/search',
        'query' => 'reset=1',
        'title' => '搜尋活動參加者',
        'menu' => 'primary-links',
        'weight' => '-49',
        'module' => 'menu',
        'hidden' => '0',
      ),
      6 => 
      array (
        'path' => 'civicrm/event/import',
        'query' => 'reset=1',
        'title' => '匯入參加者',
        'menu' => 'primary-links',
        'weight' => '-48',
        'module' => 'menu',
        'hidden' => '0',
      ),
      7 => 
      array (
        'path' => 'civicrm/event/add',
        'query' => 'reset=1&action=add',
        'title' => '新增活動',
        'menu' => 'primary-links',
        'weight' => '-47',
        'module' => 'menu',
        'hidden' => '0',
      ),
      8 => 
      array (
        'path' => 'civicrm/event/manage',
        'query' => 'reset=1',
        'title' => '管理活動',
        'menu' => 'primary-links',
        'weight' => '-46',
        'module' => 'menu',
        'hidden' => '0',
      ),
      9 => 
      array (
        'path' => 'civicrm/admin/eventTemplate',
        'query' => 'reset=1',
        'title' => '活動範本',
        'menu' => 'primary-links',
        'weight' => '-45',
        'module' => 'menu',
        'hidden' => '0',
      ),
      10 => 
      array (
        'path' => 'civicrm/admin/price',
        'query' => 'reset=1&action=add',
        'title' => '新增價格表',
        'menu' => 'primary-links',
        'weight' => '-44',
        'module' => 'menu',
        'hidden' => '0',
      ),
      11 => 
      array (
        'path' => 'civicrm/admin/price',
        'query' => 'reset=1',
        'title' => '管理價格表',
        'menu' => 'primary-links',
        'weight' => '-43',
        'module' => 'menu',
        'hidden' => '0',
      ),
    ),
  ),
  3 => 
  array (
    'path' => 'civicrm/mailing/browse',
    'query' => 'reset=1&scheduled=true',
    'title' => '電子報',
    'menu' => 'primary-links',
    'weight' => '-46',
    'module' => 'menu',
    'expanded' => 1,
    'hidden' => '0',
    'children' => 
    array (
      0 => 
      array (
        'path' => 'civicrm/mailing/send',
        'query' => 'reset=1',
        'title' => '新增電子報/郵件',
        'menu' => 'primary-links',
        'weight' => '-50',
        'module' => 'menu',
        'hidden' => '0',
      ),
      1 => 
      array (
        'path' => 'civicrm/mailing/browse/unscheduled',
        'query' => 'reset=1&scheduled=false',
        'title' => '草稿與未排程的電子報',
        'menu' => 'primary-links',
        'weight' => '-49',
        'module' => 'menu',
        'hidden' => '0',
      ),
      2 => 
      array (
        'path' => 'civicrm/mailing/browse/scheduled',
        'query' => 'reset=1&scheduled=true',
        'title' => '已排程與已寄送的電子報',
        'menu' => 'primary-links',
        'weight' => '-48',
        'module' => 'menu',
        'hidden' => '0',
      ),
      3 => 
      array (
        'path' => 'civicrm/mailing/browse/archived',
        'query' => 'reset=1',
        'title' => '電子報存檔',
        'menu' => 'primary-links',
        'weight' => '-47',
        'module' => 'menu',
        'hidden' => '0',
      ),
      4 => 
      array (
        'path' => 'civicrm/admin/component',
        'query' => 'reset=1',
        'title' => '頁首、頁尾、自動回覆訊息',
        'menu' => 'primary-links',
        'weight' => '-46',
        'module' => 'menu',
        'hidden' => '0',
      ),
      5 => 
      array (
        'path' => 'civicrm/admin/messageTemplates',
        'query' => 'reset=1',
        'title' => '訊息範本',
        'menu' => 'primary-links',
        'weight' => '-45',
        'module' => 'menu',
        'hidden' => '0',
      ),
      6 => 
      array (
        'path' => 'civicrm/admin/options/from_email',
        'query' => 'group=from_email_address&reset=1',
        'title' => 'Email寄件者',
        'menu' => 'primary-links',
        'weight' => '-44',
        'module' => 'menu',
        'hidden' => '0',
      ),
      7 => 
      array (
        'path' => 'civicrm/admin/options/email_greeting',
        'query' => 'group=email_greeting&reset=1',
        'title' => 'Email問候語',
        'menu' => 'primary-links',
        'weight' => '-43',
        'module' => 'menu',
        'hidden' => '0',
      ),
    ),
  ),
  4 => 
  array (
    'path' => 'civicrm/member',
    'query' => 'reset=1',
    'title' => '會員',
    'menu' => 'primary-links',
    'weight' => '-45',
    'module' => 'menu',
    'hidden' => '0',
    'expanded' => 1,
    'children' => 
    array (
      0 => 
      array (
        'path' => 'civicrm/member/add',
        'query' => 'reset=1&action=add&context=standalone',
        'title' => '新增會員資料',
        'menu' => 'primary-links',
        'weight' => '-50',
        'module' => 'menu',
        'hidden' => '0',
      ),
      1 => 
      array (
        'path' => 'civicrm/member/search',
        'query' => 'reset=1',
        'title' => '搜尋會員',
        'menu' => 'primary-links',
        'weight' => '-49',
        'module' => 'menu',
        'hidden' => '0',
      ),
      2 => 
      array (
        'path' => 'civicrm/member/import',
        'query' => 'reset=1',
        'title' => '匯入會員',
        'menu' => 'primary-links',
        'weight' => '-48',
        'module' => 'menu',
        'hidden' => '0',
      ),
      3 => 
      array (
        'path' => 'civicrm/admin/member/membershipType',
        'query' => 'reset=1',
        'title' => '新增/編輯會員類型',
        'menu' => 'primary-links',
        'weight' => '-47',
        'module' => 'menu',
        'hidden' => '0',
      ),
      4 => 
      array (
        'path' => 'civicrm/admin/member/membershipStatus',
        'query' => 'reset=1',
        'title' => '新增/編輯會員狀態',
        'menu' => 'primary-links',
        'weight' => '0',
        'module' => 'menu',
        'hidden' => '0',
      ),
    ),
  ),
  5 => 
  array (
    'path' => 'civicrm/report/list',
    'query' => 'reset=1',
    'title' => '報表',
    'menu' => 'primary-links',
    'weight' => '-44',
    'module' => 'menu',
    'hidden' => '0',
    'expanded' => 1,
    'children' => 
    array (
      0 => 
      array (
        'path' => 'civicrm/admin/report/template/list',
        'query' => 'reset=1',
        'title' => '從範本新增報表',
        'menu' => 'primary-links',
        'weight' => '2',
        'module' => 'menu',
        'hidden' => '0',
      ),
      1 => 
      array (
        'path' => 'civicrm/admin/report/options/report_template&reset=1',
        'query' => NULL,
        'title' => '報表範本管理',
        'menu' => 'primary-links',
        'weight' => '0',
        'module' => 'menu',
        'hidden' => '0',
      ),
    ),
  ),
);
 
$menu_links['menu-footer'] =array (
  0 => 
  array (
    'path' => 'http://netivism.com.tw/about',
    'query' => NULL,
    'title' => '關於網絡行動科技',
    'menu' => 'menu-footer',
    'weight' => '2',
    'module' => 'menu',
    'hidden' => '0',
  ),
  1 => 
  array (
    'path' => 'http://civicrm.org/aboutcivicrm',
    'query' => NULL,
    'title' => '關於CiviCRM',
    'menu' => 'menu-footer',
    'weight' => '3',
    'module' => 'menu',
    'hidden' => '0',
  ),
);

$menu_links['menu-search'] = array (
  0 => 
  array (
    'path' => 'civicrm/contact/search/builder',
    'query' => 'reset=1',
    'title' => '自定搜尋',
    'menu' => 'menu-search',
    'weight' => '4',
    'module' => 'menu',
    'hidden' => '0',
  ),
  1 => 
  array (
    'path' => 'civicrm/contact/search/custom',
    'query' => 'csid=15&reset=1',
    'title' => '全文搜尋',
    'menu' => 'menu-search',
    'weight' => '3',
    'module' => 'menu',
    'hidden' => '0',
  ),
  2 => 
  array (
    'path' => 'civicrm/contact/search/advanced',
    'query' => 'reset=1',
    'title' => '進階搜尋',
    'menu' => 'menu-search',
    'weight' => '2',
    'module' => 'menu',
    'hidden' => '0',
  ),
);
