<?php

/**
 * Implementation of hook_menu()
 */
function esunbank_menu(){
  return array(
    'esunbank/%/%' => array(
      'page callback' => 'esunbank_api_test',
      'page arguments' => array(1),
      'access arguments' => array('access administration pages'),
      'type' => MENU_CALLBACK,
      'file' => 'esunbank.api.inc',
    ),
  );
}

function esunbank_api_test($func, $code, $a, $b){
  if(function_exists($func)){
    return call_user_func($func, $code, $a, $b);
  }
}
