<?php

define('DEMO_CONTACT_NUM', 200);
define('DEMO_CONTRIBUTE_NUM', 5000);
define('DEMO_EVENT_NUM', 5);
define('DEMO_PARTICIPANT_NUM', 20);

/**
 * Implementation of hook_menu().
 */

function civicrm_demo_menu(){
  return array(
    'admin/settings/civicrm_demo' => array(
      'title'            => 'Generate demo data of CiviCRM',
      'access arguments' => array('administer site configuration'),
      'page callback'    => 'drupal_get_form',
      'page arguments'    => array('civicrm_demo_settings'),
    )
  );
}

function civicrm_demo_settings(){
  $form['options'] = array(
    '#type' => 'checkboxes',
    '#required' => true,
    '#title' => t('Data'),
    '#options' => array(
      'contact' => t('Contact'),
      'contribution' => t('Contribution'),
      'event' => t('Event and Participant'),
      'member' => t('Member'),
    ),
  );
  $form['start_year'] = array(
    '#type' => 'textfield',
    '#title' => t('Start year'),
    '#default_value' => date('Y', (time() - 86400*5*365) ),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Generate'),
  );
  return $form;
}
function civicrm_demo_settings_submit($form, &$form_state){
  set_time_limit(1200);
  $options = $form_state['values']['options'];
  foreach($options as $function){
    $function = 'civicrm_demo_process_'.$function;
    if(function_exists($function)){
      $function($form_state['values']);
    }
  }
}

function civicrm_demo_process_contact($vars){
  civicrm_initialize();
  require_once("api/v2/Contact.php");
  require_once 'api/v2/Location.php';

  $limit = DEMO_CONTACT_NUM;
  while($limit) {
    // 10% to generate eng name
    $language = mt_rand(1,10) == 1 ? 'english' : 'chinese';
    $params = array(
      'first_name'    => _civicrm_demo_rand_firstname($language),
      'last_name'     => _civicrm_demo_rand_lastname($language),
      'email'         => _civicrm_demo_rand_email(),
      'contact_type'  => 'Individual',
      'individual_prefix' => _civicrm_demo_rand_prefix(),
      'gender_id' => mt_rand(1,2),
      'birth_date' => _civicrm_demo_rand_birth(),
    );
    $contact =& civicrm_contact_create( $params );

    $home_phone = array(
      'phone' => '0'.mt_rand(2,39).'-'.mt_rand(1111111, 9999999),
      'phone_type_id' => 1,
      'location_type' => 'Home'
    );
    $fax_phone = array(
      'phone' => '0'.mt_rand(2,39).'-'.mt_rand(1111111, 9999999),
      'phone_type_id' =>  2,
      'is_primary' => TRUE,
      'location_type_id' => 2
    );
    $address = _civicrm_demo_rand_addr($language);
    $phones = array( $homePhone, $faxPhone);
    $params = array(
      'version'    => '3.0',
      'contact_id' => $contact['contact_id'],
      'phone'      => $phones,
      'address'    => $address
    );
    $newLocation =& civicrm_location_add($params);

    $limit--;
  }
  drupal_set_message(t("Successful generate data of !type", array('!type' => t('Contact') )));
}

function civicrm_demo_process_event($vars){
  civicrm_initialize();
  require_once "api/v2/Event.php";
  require_once "api/v2/Participant.php";
  require_once("api/v2/Contact.php");
  $now = time();

  // create 5 events
  for($i=0;  $i<DEMO_EVENT_NUM; $i++){
    $seed = mt_rand(0,4);
    $title = array(
      '實務訓練課程，開放報名',
      '網路軟體應用研討會',
      '夏季親子台灣走透透營隊',
      '生活很健康講座',
      '心靈環保與生活環保-見面會',
    );
    $params = array();
    $params['title'] = $title[$seed];
    $params['is_active'] = 1;
    $params['is_monetory'] = 0;
    $params['event_type_id'] = 1;
    $params['is_show_location'] = 0;
    $params['start_date'] = date('Ymd', $now+$i*86400*5);
    $params['end_date'] = date('Ymd', $now+$i*86400*5+7200);
    $params['registration_start_date'] = date('Ymd', $now-$i*86400*2);
    $params['registration_end_date'] = date('Ymd', $now+$i*86400*2);
    $params['max_participants'] = rand(30,50);
    $result = civicrm_event_create($params);

    $event_id = $result['event_id'];
    $params2 = array(
      'return.contact_id',
      'sort' => 'contact_id DESC',
    );
    $contacts = civicrm_contact_search($params2);

    // add participants
    $max = mt_rand(5, DEMO_PARTICIPANT_NUM);
    foreach($contacts as $contact){
      $j++;
      if($j > $max) break;
      $params3 = array();
      $params3['contact_id'] = $contact['contact_id'];
      $params3['event_id'] = $event_id;
      $params3['status_id'] = 1;
      $params3['role_id'] = 1;
      $params3['register_date'] = date('YmdHis');
      $params3['source'] = '示範用途';
      $result3 = civicrm_participant_create($params3);
    }
  }

  drupal_set_message(t("Successful generate data of !type", array('!type' => t('Event') )));
}

function civicrm_demo_process_contribution($vars){
  civicrm_initialize();
  require_once("api/v2/Contact.php");
  require_once("api/v2/Contribute.php");

  // query exists contact
  $sql = "SELECT id FROM civicrm_contact WHERE is_deleted = 0";
  $dao = CRM_Core_DAO::executeQuery($sql);

  // prepare variable
  $contribution_page_id = 1;
  $contribution_type_id = 1;
  $payment_instrument_id = 1;
  $start_year = $vars['start_year'];
  $limit = 50; // limit every contact only have 50 record of contribution.

  // start
  while($dao->fetch()){
    $contact_id = $dao->id;
    for($i = 0; $i < $limit; $i++){
      $counter++;
      if($counter > DEMO_CONTRIBUTE_NUM) break; 
      $amount = mt_rand(300, 12000);
      $a = number_format($amount, 2, '.', '');
      $fee = number_format($amount*0.025, 2, '.', '');

      $year = mt_rand($start_year, date('Y'));
      $month = sprintf('%02s',mt_rand(1,date('n')));
      if($year == date('Y') ){
        $day = sprintf('%02s', mt_rand(1,28));
      }
      else{
        $day = sprintf('%02s', mt_rand(1,date('j')));
      }

      $params = array(
        'contact_id'             => $contact_id,
        'receive_date'           => $year.$month.$day,
        'total_amount'           => $a,
        'payment_instrument_id'  => $payment_instrument_id,
        'fee_amount'             => $fee,
        'contribution_status_id' => 1,
        'contribution_type_id' => $contribution_type_id,
        'contribution_page_id' => $contribution_page_id,
      );

      $contrib = civicrm_contribution_add($params);
    }
  }

  drupal_set_message(t("Successful generate data of !type", array('!type' => t('Contribution') )));
}

function _civicrm_demo_rand_lastname($type = 'chinese'){
  // chinese
  if($type == 'chinese'){
    $seed = array(
      '李','王','張','劉','陳','楊','黃','趙','周','吳','徐','孫','朱','馬','胡','郭','林','何','高','梁','鄭','羅','宋','謝','唐','韓','曹','許','鄧','蕭',' 馮','曾','程','蔡','彭','潘','袁','于','董','余',' 蘇','葉','呂','魏','蔣','田','杜','丁','沈','姜',' 范','江','傅','鍾','盧','汪','戴','崔','任','陸',' 廖','姚','方','金','邱','夏','譚','韋','賈','鄒',' 石','熊','孟','秦','閻','薛','侯','雷','白','龍','段','郝','孔','邵','史','毛','常','萬','顧','賴','武','康','賀','嚴','尹','錢','施','牛','洪','龔',
    );
  }
  else{
    $seed = array(
      'Smith','Johnson','Williams','Brown','Jones','Miller','Davis','García','Rodríguez','Wilson','Martínez','Anderson','Taylor','Thomas','Hernández','Moore','Martin','Jackson','Thompson','White','López','Lee','González','Harris','Clark','Lewis','Robinson','Walker','Pérez','Hall','Young','Allen','Sánchez','Wright','King','Scott','Green','Baker','Adams','Nelson','Hill','Ramírez','Campbell','Mitchell','Roberts','Carter','Phillips','Evans','Turner','Torres','Parker','Collins','Edwards','Stewart','Flores','Morris','Nguyen','Murphy','Rivera','Cook','Rogers','Morgan','Peterson','Cooper','Reed','Bailey','Bell','Gómez','ward','Ward','Cox','Díaz','Richardson','Wood','Watson','Brooks','Bennett','Gray','James','Reyes','Cruz','Hughes','Price','Myers','Long','Foster','Sanders','Ross','Morales','Powell','Sullivan','Russell','Ortiz','Jenkins','Gutiérrez','Perry','Butler','Barnes','Fisher', 
    );
  }
  $key = array_rand($seed);
  return $seed[$key];
}

function _civicrm_demo_rand_firstname($type = 'chinese'){
  // chinese
  if($type == 'chinese'){
    $seed = array(
      '雅婷 ','怡君 ','雅雯 ','宗翰 ','怡婷 ','家豪 ','冠宇 ','詩涵 ','婉婷 ','承翰 ','郁婷 ','柏翰 ','彥廷 ','詩婷 ','鈺婷 ','冠廷 ','佩珊 ','欣怡 ','家瑋 ','思穎 ','佳蓉 ','佳穎','志豪','怡萱','筱涵',
    );
  }
  else{
    $seed = array(
      'Jacob','Ethan','Michael','Jayden','William','Alexander','Noah','Daniel','Aiden','Anthony',
      'Isabella','Mia','Ashley','Emily','Sophia','Brianna','Melanie','Samantha','Genesis','Kayla',
    );
  }
  $key = array_rand($seed);
  return $seed[$key];
}

function _civicrm_demo_rand_birth(){
  $base = time()-86400*365*3;
  $time = mt_rand(0, $base);
  $prev = mt_rand(0, 1);
  if($prev){
    $time = 0-$time;
  }
  return date('YMDHis', $time);
}

function _civicrm_demo_rand_prefix(){
  $array = array(
    '女士',
    '小姐',
    '先生',
  );
  $seed = mt_rand(0,2);
  return $array[$seed];
}

function _civicrm_demo_rand_email(){
  $name = trim(strtolower(_civicrm_demo_rand_firstname('english'))).'.'.trim(strtolower(_civicrm_demo_rand_lastname('english')));
  $company = array(
    'example.com','test.tw','ilovecivicrm.com','netivism-is-best.com.tw',
  );
  $key = array_rand($company);
  return $name.'@'.$company[$key];
}

function _civicrm_demo_rand_addr($type = 'chinese'){
  if($type == 'chinese'){
    $sp = array(
      'Changhua County','Chiayi City','Chiayi County','Hsinchu City','Hsinchu County','Hualien County','Ilan County','Kaohsiung City','Keelung City','Kinmen County','Lienchiang County','Miaoli County','Nantou County','Penghu County','Pingtung County','Taichung City','Tainan City','Taipei City','Taipei County','Taitung County','Taoyuan County','Yunlin Conuty',
    );
    $seed = array_rand($sp);
    $state_province = $sp[$seed];
    list($city, $postal_code) = _civicrm_demo_rand_city_postcode($sp[$seed]);
    $street = '中山路1段1號';
    $country = 1208;
  }
  else{
    $state_province = 'California';
    $city = 'San Francisco';
    $street = rand(1,800).', FC Road';
    $country = 1228;
  }

  $address = array(
    1 => array(
      'location_type_id'       => 1,
      'is_primary'             => 1,
      'city'                   => $city,
      'state_province'         => $state_province,
      'street_address'         => $street,
      'country_id'             => $country,
    )
  );
  return $address;
}

function _civicrm_demo_rand_city_postcode($city){
  $array = array(
    'Keelung City' => array(
      '仁愛區' => '200', '信義區' => '201', '中正區' => '202', '中山區' => '203', '安樂區' => '204', '暖暖區' => '205', '七堵區' => '206'
    ),
    'Taipei City' => array(
      '中正區' => '100', '大同區' => '103', '中山區' => '104', '松山區' => '105', '大安區' => '106', '萬華區' => '108', '信義區' => '110', '士林區' => '111', '北投區' => '112', '內湖區' => '114', '南港區' => '115', '文山區' => '116'
    ),
    'Taipei County' => array(
      '萬里區' => '207', '金山區' => '208', '板橋區' => '220', '汐止區' => '221', '深坑區' => '222', '石碇區' => '223',
      '瑞芳區' => '224', '平溪區' => '226', '雙溪區' => '227', '貢寮區' => '228', '新店區' => '231', '坪林區' => '232',
      '烏來區' => '233', '永和區' => '234', '中和區' => '235', '土城區' => '236', '三峽區' => '237', '樹林區' => '238',
      '鶯歌區' => '239', '三重區' => '241', '新莊區' => '242', '泰山區' => '243', '林口區' => '244', '蘆洲區' => '247',
      '五股區' => '248', '八里區' => '249', '淡水區' => '251', '三芝區' => '252', '石門區' => '253'
    ),
    'Ilan County' => array(
      '宜蘭市' => '260', '頭城鎮' => '261', '礁溪鄉' => '262', '壯圍鄉' => '263', '員山鄉' => '264', '羅東鎮' => '265',
      '三星鄉' => '266', '大同鄉' => '267', '五結鄉' => '268', '冬山鄉' => '269', '蘇澳鎮' => '270', '南澳鄉' => '272',
      '釣魚台列嶼' => '290'
    ),
    'Hsinchu City' => array(
      '新竹市' => '300'
    ),
    'Hsinchu County' => array(
      '竹北市' => '302', '湖口鄉' => '303', '新豐鄉' => '304', '新埔鎮' => '305', '關西鎮' => '306', '芎林鄉' => '307',
      '寶山鄉' => '308', '竹東鎮' => '310', '五峰鄉' => '311', '橫山鄉' => '312', '尖石鄉' => '313', '北埔鄉' => '314',
      '峨嵋鄉' => '315'
    ),
    'Taoyuan County' => array(
      '中壢市' => '320', '平鎮市' => '324', '龍潭鄉' => '325', '楊梅鎮' => '326', '新屋鄉' => '327', '觀音鄉' => '328',
      '桃園市' => '330', '龜山鄉' => '333', '八德市' => '334', '大溪鎮' => '335', '復興鄉' => '336', '大園鄉' => '337',
      '蘆竹鄉' => '338'
    ),
    'Miaoli County' => array(
      '竹南鎮' => '350', '頭份鎮' => '351', '三灣鄉' => '352', '南庄鄉' => '353', '獅潭鄉' => '354', '後龍鎮' => '356',
      '通霄鎮' => '357', '苑裡鎮' => '358', '苗栗市' => '360', '造橋鄉' => '361', '頭屋鄉' => '362', '公館鄉' => '363',
      '大湖鄉' => '364', '泰安鄉' => '365', '銅鑼鄉' => '366', '三義鄉' => '367', '西湖鄉' => '368', '卓蘭鎮' => '369'
    ),
    'Taichung City' => array('中區' => '400', '東區' => '401', '南區' => '402', '西區' => '403', '北區' => '404', '北屯區' => '406',
      '西屯區' => '407', '南屯區' => '408',
      '太平區' => '411', '大里區' => '412', '霧峰區' => '413', '烏日區' => '414', '豐原區' => '420', '后里區' => '421',
      '石岡區' => '422', '東勢區' => '423', '和平區' => '424', '新社區' => '426', '潭子區' => '427', '大雅區' => '428',
      '神岡區' => '429', '大肚區' => '432', '沙鹿區' => '433', '龍井區' => '434', '梧棲區' => '435', '清水區' => '436',
      '大甲區' => '437', '外埔區' => '438', '大安區' => '439'
    ),
    'Changhua County' => array(
      '彰化市' => '500', '芬園鄉' => '502', '花壇鄉' => '503', '秀水鄉' => '504', '鹿港鎮' => '505', '福興鄉' => '506',
      '線西鄉' => '507', '和美鎮' => '508', '伸港鄉' => '509', '員林鎮' => '510', '社頭鄉' => '511', '永靖鄉' => '512',
      '埔心鄉' => '513', '溪湖鎮' => '514', '大村鄉' => '515', '埔鹽鄉' => '516', '田中鎮' => '520', '北斗鎮' => '521',
      '田尾鄉' => '522', '埤頭鄉' => '523', '溪州鄉' => '524', '竹塘鄉' => '525', '二林鎮' => '526', '大城鄉' => '527',
      '芳苑鄉' => '528', '二水鄉' => '530'
    ),
    'Nantou County' => array(
      '南投市' => '540', '中寮鄉' => '541', '草屯鎮' => '542', '國姓鄉' => '544', '埔里鎮' => '545', '仁愛鄉' => '546',
      '名間鄉' => '551', '集集鎮' => '552', '水里鄉' => '553', '魚池鄉' => '555', '信義鄉' => '556', '竹山鎮' => '557',
      '鹿谷鄉' => '558'
    ),
    'Chiayi County' => array(
      '嘉義市' => '600'
    ),
    'Chiayi City' => array(
      '番路鄉' => '602', '梅山鄉' => '603', '竹崎鄉' => '604', '阿里山' => '605', '中埔鄉' => '606', '大埔鄉' => '607',
      '水上鄉' => '608', '鹿草鄉' => '611', '太保市' => '612', '朴子市' => '613', '東石鄉' => '614', '六腳鄉' => '615',
      '新港鄉' => '616', '民雄鄉' => '621', '大林鎮' => '622', '溪口鄉' => '623', '義竹鄉' => '624', '布袋鎮' => '625'
    ),
    'Yunlin Conuty' => array(
      '斗南鎮' => '630', '大埤鄉' => '631', '虎尾鎮' => '632', '土庫鎮' => '633', '褒忠鄉' => '634', '東勢鄉' => '635',
      '臺西鄉' => '636', '崙背鄉' => '637', '麥寮鄉' => '638', '斗六市' => '640', '林內鄉' => '643', '古坑鄉' => '646',
      '莿桐鄉' => '647', '西螺鎮' => '648', '二崙鄉' => '649', '北港鎮' => '651', '水林鄉' => '652', '口湖鄉' => '653',
      '四湖鄉' => '654', '元長鄉' => '655'
    ),
    'Tainan City' => array('中西區' => '700', '東區' => '701', '南區' => '702', '北區' => '704', '安平區' => '708', '安南區' => '709',
      '永康區' => '710', '歸仁區' => '711', '新化區' => '712', '左區區' => '713', '玉井區' => '714', '楠西區' => '715',
      '南化區' => '716', '仁德區' => '717', '關廟區' => '718', '龍崎區' => '719', '官田區' => '720', '麻豆區' => '721',
      '佳里區' => '722', '西港區' => '723', '七股區' => '724', '將軍區' => '725', '學甲區' => '726', '北門區' => '727',
      '新營區' => '730', '後壁區' => '731', '白河區' => '732', '東山區' => '733', '六甲區' => '734', '下營區' => '735',
      '柳營區' => '736', '鹽水區' => '737', '善化區' => '741', '大內區' => '742', '山上區' => '743', '新區區' => '744',
      '安定區' => '745'
    ),
    'Kaohsiung City' => array(
      '新興區' => '800', '前金區' => '801', '苓雅區' => '802', '鹽埕區' => '803', '鼓山區' => '804', '旗津區' => '805',
      '前鎮區' => '806', '三民區' => '807', '楠梓區' => '811', '小港區' => '812', '左營區' => '813',
      '仁武區' => '814', '大社區' => '815', '岡山區' => '820', '路竹區' => '821', '阿蓮區' => '822', '田寮區' => '823',
      '燕巢區' => '824', '橋頭區' => '825', '梓官區' => '826', '彌陀區' => '827', '永安區' => '828', '湖內區' => '829',
      '鳳山區' => '830', '大寮區' => '831', '林園區' => '832', '鳥松區' => '833', '大樹區' => '840', '旗山區' => '842',
      '美濃區' => '843', '六龜區' => '844', '內門區' => '845', '杉林區' => '846', '甲仙區' => '847', '桃源區' => '848',
      '那瑪夏區' => '849', '茂林區' => '851', '茄萣區' => '852'
    ),
    'Pingtung County' => array(
      '屏東市' => '900', '三地門' => '901', '霧臺鄉' => '902', '瑪家鄉' => '903', '九如鄉' => '904', '里港鄉' => '905',
      '高樹鄉' => '906', '鹽埔鄉' => '907', '長治鄉' => '908', '麟洛鄉' => '909', '竹田鄉' => '911', '內埔鄉' => '912',
      '萬丹鄉' => '913', '潮州鎮' => '920', '泰武鄉' => '921', '來義鄉' => '922', '萬巒鄉' => '923', '崁頂鄉' => '924',
      '新埤鄉' => '925', '南州鄉' => '926', '林邊鄉' => '927', '東港鎮' => '928', '琉球鄉' => '929', '佳冬鄉' => '931',
      '新園鄉' => '932', '枋寮鄉' => '940', '枋山鄉' => '941', '春日鄉' => '942', '獅子鄉' => '943', '車城鄉' => '944',
      '牡丹鄉' => '945', '恆春鎮' => '946', '滿州鄉' => '947'
    ),
    'Taitung County' => array(
      '臺東市' => '950', '綠島鄉' => '951', '蘭嶼鄉' => '952', '延平鄉' => '953', '卑南鄉' => '954', '鹿野鄉' => '955',
      '關山鎮' => '956', '海端鄉' => '957', '池上鄉' => '958', '東河鄉' => '959', '成功鎮' => '961', '長濱鄉' => '962',
      '太麻里鄉' => '963', '金峰鄉' => '964', '大武鄉' => '965', '達仁鄉' => '966'
    ),
    'Hualien County' => array(
      '花蓮市' => '970', '新城鄉' => '971', '秀林鄉' => '972', '吉安鄉' => '973', '壽豐鄉' => '974', '鳳林鎮' => '975',
      '光復鄉' => '976', '豐濱鄉' => '977', '瑞穗鄉' => '978', '萬榮鄉' => '979', '玉里鎮' => '981', '卓溪鄉' => '982',
      '富里鄉' => '983'
    ),
    'Linmen County' => array(
      '金沙鎮' => '890', '金湖鎮' => '891', '金寧鄉' => '892', '金城鎮' => '893', '烈嶼鄉' => '894', '烏坵鄉' => '896'
     ),
    'Lienchiang County' => array(
      '南竿鄉' => '209', '北竿鄉' => '210', '莒光鄉' => '211', '東引鄉' => '212'
    ),
    'Penghu County' => array(
      '馬公市' => '880', '西嶼鄉' => '881', '望安鄉' => '882', '七美鄉' => '883', '白沙鄉' => '884', '湖西鄉' => '885'
    ),
  );
  $key = array_rand($array[$city]);
  $return = array($key , $array[$city][$key]);
  return $return;
}
