<?php

/**
 * Implementation of hook_menu().
 */

function civicrm_demo_menu(){
  return array(
    'admin/settings/civicrm_demo' => array(
      'title'            => 'Generate demo data of CiviCRM',
      'access arguments' => array('administer site configuration'),
      'page callback'    => 'drupal_get_form',
      'page arguments'    => array('civicrm_demo_settings'),
    )
  );
}

function civicrm_demo_settings(){
  $form['options'] = array(
    '#type' => 'checkboxes',
    '#required' => true,
    '#title' => t('Data'),
    '#options' => array(
    //  'contact' => t('Contact'),
      'contribution' => t('Contribution'),
    //  'event' => t('Event and Participant'),
    //  'member' => t('Member'),
    ),
  );
  $form['start_year'] = array(
    '#type' => 'textfield',
    '#title' => t('Start year'),
    '#default_value' => date('Y', (time() - 86400*5*365) ),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Generate'),
  );
  return $form;
}
function civicrm_demo_settings_submit($form, &$form_state){
  set_time_limit(1200);
  $options = $form_state['values']['options'];
  foreach($options as $function){
    $function = 'civicrm_demo_process_'.$function;
    if(function_exists($function)){
      $function($form_state['values']);
    }
  }
}

function civicrm_demo_process_contact($vars){
}

function civicrm_demo_process_contribution($vars){
  civicrm_initialize();
  require_once("api/v2/Contact.php");
  require_once("api/v2/Contribute.php");

  // query exists contact
  $sql = "SELECT id FROM civicrm_contact WHERE is_deleted = 0";
  $dao = CRM_Core_DAO::executeQuery($sql);

  // prepare variable
  $contribution_page_id = 1;
  $contribution_type_id = 1;
  $payment_instrument_id = 1;
  $start_year = $vars['start_year'];
  $limit = 50; // limit every contact only have 50 record of contribution.

  // start
  while($dao->fetch()){
    $contact_id = $dao->id;
    for($i = 0; $i < $limit; $i++){
      $amount = rand(500, 10000);
      $a = number_format($amount, 2, '.', '');
      $fee = number_format($amount*0.025, 2, '.', '');

      $year = rand($start_year, date('Y'));
      $month = sprintf('%02s',rand(1,12));
      $day = sprintf('%02s', rand(1,28));

      $params = array(
        'contact_id'             => $contact_id,
        'receive_date'           => $year.$month.$day,
        'total_amount'           => $a,
        'payment_instrument_id'  => $payment_instrument_id,
        'fee_amount'             => $fee,
        'contribution_status_id' => 1,
        'contribution_type_id' => $contribution_type_id,
        'contribution_page_id' => $contribution_page_id,
      );

      $contrib = civicrm_contribution_add($params);
    }
  }

  drupal_set_message(t("Successful generate data of !type", array('!type' => t('Contribution') )));
}
