<?php
define("NETICRM_DEFAULT_URL", "http://civicrm.netivism.com.tw/neticrm/statistics");

function civicrm_statistics_cron(){
  if($_SERVER['REQUEST_TIME'] - variable_get('civicrm_statistics_run', 0) > 86399){
    civicrm_statistics_check_update();
  }
}

function civicrm_statistics_check_update(){
  global $base_url;
  $tables = array(
    'civicrm_contact' => 'cc',
    'civicrm_contribution' => 'ccb',
    'civicrm_contribution.amount' => 'ccb.a',
    'civicrm_contribution_page' => 'ccp',
    'civicrm_mailing_event_delivered' => 'cmed',
    'civicrm_mailing_event_opened' => 'cmeo',
    'civicrm_mailing_event_trackable_url_open' => 'cmet',
    'civicrm_event' => 'ce',
    'civicrm_participant' => 'cp',
  );

  $sitekey = md5($base_url . drupal_get_private_key());
  civicrm_initialize();
  foreach($tables as $table => $t){
    if(strpos($table, '_contribution')){
      if(strpos($table, 'amount')){
        $rows = CRM_Core_DAO::singleValueQuery("SELECT SUM(total_amount) FROM civicrm_contribution WHERE contribution_status_id = 1");
        $rows = (int) $rows;
      }
      else{
        $rows = CRM_Core_DAO::singleValueQuery("SELECT COUNT(*) FROM civicrm_contribution WHERE contribution_status_id = 1");
      }
    }
    else{
      $query = CRM_Core_DAO::executeQuery("SHOW TABLE STATUS LIKE '$table'");
      $query->fetch();
      $rows = $query->Rows;
    }

    $url = civicrm_statistics_build_fetch_url($sitekey, $t, $rows);
    // $json = drupal_http_request($url);
    $response = drupal_http_request($url);
    variable_set('civicrm_statistics_run', $_SERVER['REQUEST_TIME']);
  }
}

function civicrm_statistics_build_fetch_url($sitekey, $type, $stat){
  return NETICRM_DEFAULT_URL."/add?sitekey={$sitekey}&type={$type}&stat={$stat}";
}

