<?php
function civicrm_participant_serial_civicrm_buildForm($form_name, &$form){
  switch($form_name){
    case 'CRM_Event_Form_Registration_AdditionalParticipant':
    case 'CRM_Event_Form_Registration_Register':
      // hide serial field
      $cid = _civicrm_participant_serial();
      $c_field = 'custom_'.$cid;
      drupal_add_js('$(document).ready(function(){  $(".'.$c_field.'-section").hide(); });', 'inline');
      break;
  }
}

function civicrm_participant_serial_civicrm_preSave($form_name, &$form){
  switch($form_name){
    case 'CRM_Event_Form_Registration_AdditionalParticipant':
    case 'CRM_Event_Form_Registration_Register':
      $event_id = $form->getVar('_eventId');
      $is_test = $form->getVar('_mode') == 'test' ? 1 : 0;
      if($cid = variable_get('civicrm_participant_serial', '17')){
        $query = "SELECT cg.table_name, cg.id, cf.column_name, cf.id as fid FROM   civicrm_custom_group cg, civicrm_custom_field cf WHERE cf.custom_group_id = cg.id AND cg.is_active = 1  AND cf.is_active = 1 AND cf.id = $cid";
        $dao = CRM_Core_DAO::executeQuery($query);
        if($dao->fetch()){
          if($dao->table_name && $dao->column_name){
            // try to direct control session value
            $session_id = '_'.$form->controller->_name.'_container';

            foreach($_SESSION[$session_id]['values'] as $k => $v){
              if(isset($v['custom_'.$cid])){
                $count++;
                $query = "SELECT t.{$dao->column_name} as serial FROM {$dao->table_name} t INNER JOIN civicrm_participant p ON p.id = t.entity_id WHERE p.event_id = {$event_id} AND p.is_test = {$is_test} ORDER BY t.{$dao->column_name} DESC";
                $sid = CRM_Core_DAO::singleValueQuery($query);
                if($sid){
                  $sid+=$count;
                }
                else{
                  $sid = 0 + $count;
                }
                $_SESSION[$session_id]['values'][$k]['custom_'.$cid] = $sid;
              }
            }

          }
        }
        
      }
      break;
  }
}

function _civicrm_participant_serial(){
  if($cid = variable_get('civicrm_participant_serial', '17')){
    return $cid;
  }
  /*
    $result = CRM_Core_BAO_CustomField::getFields('Participant', true, true);
    foreach($result as $id => $values){
    }
    return $cid;
  */
    
}
